### DISCUSSION TITLE
email server settings don't work

### DISCUSSION THREAD

**Discussion by manilx** [fosrl/pangolin#134] [Q&A] [answered]
I've added the following to config.yml:
```
email:
    smtp_host: "smtp.gmail.com"
    smtp_port: 465
    smtp_user: "me@gmail.com"
    smtp_pass: "app_specific_pw"
    smtp_secure: true
    no_reply: "me@gmail.com"
```

Trying to invite new user but this doesn't work. The seetings should be OK and work on other services.
Also tried other smtp servers with same issue.
