### DISCUSSION TITLE
GeoIP blocking

### DISCUSSION THREAD

**Discussion by manilx** [fosrl/pangolin#135] [Feature Requests]
Zoraxy has a great feature in that I can have whitelist or blacklist with GeoIP blocking.
I have only 2 countries in the whitelist. All other are blocked.

This is the one feature I would REALLY miss.....

**Comment by manilx** [comment]
AN iP block list would be great also.

**Comment by manilx** [comment]
@miloschwartz @oschwartz10612 Have a look at this: https://github.com/fabriziosalmi/caddy-waf   https://github.com/fabriziosalmi/caddy-mib
Something like this in Pangolin!

**Comment by projektug24** [comment]
Hi everyone,

I find the idea of GeoIP blocking really interesting and would love to see this feature implemented in a future update for Pangolin. It would be great to have the ability to block specific countries or allow only selected ones, similar to what other tools.

I believe this would be a fantastic addition to Pangolin's security features and would appeal to many users. Are there any plans to implement something like this in the future? Thanks in advance for your feedback!

Thank you for the great work and for considering this suggestion!

**Comment by TheDietrich** [comment]
Yeah, a geoIp filter would be great

**Comment by ilco3** [comment]
dont know if this  traefik pluggin could help

but i can block ip adresses based on country 
 https://plugins.traefik.io/plugins/62947313ffc0cd18356a97ca/geo-block

**Reply by manilx** [reply]
Would certainly help a lot. Problem is I don't have a clue on how to configure this.
I would need simple copy/paste instructions to put into the latest pangolin config files (created by latest installer) ¯\_(ツ)_/¯

**Reply by miloschwartz** [reply]
Yes, pretty sure you can use existing Traefik plugins to do this. We have had some people successfully do this in our Discord. Here is a link to the community guide and the thread in Discord if you're curious:

https://forum.hhf.technology/t/implementing-geoblocking-in-pangolin-stack-with-traefik
https://discord.com/channels/1325658630518865980/1339957387586568304

**Reply by manilx** [reply]
tried the discord explanation and got: ERR entryPointName=websecure routerName=14-router@http error=middleware "pangolin-geoblock@file" does not exist

Don't know what is wrong. Just copied and pastes the examples into the respective files.

**Reply by miloschwartz** [reply]
Looks like this has come up in that thread. I found this: https://discord.com/channels/1325658630518865980/1339957387586568304/1340117112852840555

**Comment by manilx** [comment]
Got it. Was an indentation issue. It's now blocking BUT it's blocking me now 😞 Dowsn't seem to to recognize my country albeight it's correctly identified in whatsmyip

**Comment by ilco3** [comment]
if i have to guese .it seems it doesnt have access to a file
***@***.***" does not exist
(i am just guessing to be clear )
 . does it need a file named pangolin-geoblock /is the spelling corect -

it also  could be copy pasting mesed up the config /formating
always check if the supplied info/config works in your setup

Op ma 10 mrt 2025 om 21:31 schreef manilx ***@***.***>:

**Comment by ilco3** [comment]
did you add your county /ip before enabling in config  . could be the
reason you are blocked

Op ma 10 mrt 2025 om 21:44 schreef manilx ***@***.***>:

**Reply by manilx** [reply]
Added this:
```
    pangolin-geoblock:
        plugin:
            geoblock:
                silentStartUp: false
                allowLocalRequests: false
                logLocalRequests: false
                logAllowedRequests: false
                logApiRequests: false
                api: "https://get.geojs.io/v1/ip/country/{ip}"
                apiTimeoutMs: 750                                 # optional
                cacheSize: 15
                forceMonthlyUpdate: false
                allowUnknownCountries: false
                unknownCountryApiResponse: "nil"
                blackListMode: false
                addCountryHeader: false
                countries:
                    - DE # Germany
                    - PT # Portugal
````

I'm in PT.

If I use ProtonVPN and choose a server in D or PT I can access my sites, but from my normal IP connection I can't. And I don't see anything blocked in the log. I just get a white page and the sites are not loading
