### DISCUSSION TITLE
Trying to get this to work with Cloudflare Tunnels

### DISCUSSION THREAD

**Discussion by JohnDoe-dev-spec** [fosrl/pangolin#153] [Q&A]
Hi,

I just wanted to say that this is a great app, and I'm keeping an eye on it as a potential replacement for my current Traefik and Authentik setup.

Currently, I'm using Cloudflare tunnels with my existing setup, and it works great. However, when I tried to use Pangolin through Cloudflare tunnels, I encountered an "ERR_TOO_MANY_REDIRECTS" error when accessing the domain set for Pangolin.

I followed the instructions from this guide and opted out of using Gerbil.

I've successfully tested Pangolin on a VPS with Newt, and it works perfectly. Ideally, I would prefer to use Cloudflare tunnels instead of purchasing a VPS.

I suspect there might be a setting in Cloudflare Tunnels causing this issue, but I haven't been able to pinpoint it.

Any help would be greatly appreciated!

**Comment by miloschwartz** [comment]
Hi, I've not tried this specifically yet, but can you describe how you're linking the Cloudflare Tunnel in a little more detail? 

Are you creating a subdomain the CF Tunnel that points to each Pangolin resource? Are you relying on CF to create the SSL certs for you? You might need to disable SSL on the Pangolin side and/or remove the TLS stuff from the Traefik config. 

I have a feeling this could be due to how the authentication cookies are set. The cookies themselves are set in the Badger middleware in Traefik, so it's possible they're not getting set according to the CF tunnel domain which is putting you in a redirect loop.

You could enable `debug` log mode for Pangolin in the config and watch the logs when the redirects happen. There may be some extra info in there that could provide some insight for us.

**Comment by JohnDoe-dev-spec** [comment]
Hi Milo,

Thank you for your reply and help so far.

Currently my Cloudflare Tunnel setup is as follows;

- Cloudflared Docker Container on same machine as Pangolin
- Wildcard for my domain so i don't have to manually add CNAMES in my cloudflare DNS (I will most likely change this in the future and use [docker-traefik-cloudflare-companion])
- Yeah, Cloudflare Tunnels provides the certificate (Current encryption mode: Full (strict))

Thanks to your suggestions i was able to resolve the redirect loop, this involved me having to comment out the Middleware http to https redirect.

This is the first time i've been able to reach the Pangolin dashboard through CF Tunnels.

My dynamic_config.yml now looks like this;


```````````````
http:
  middlewares:
    redirect-to-https:
      redirectScheme:
        scheme: https

  routers:
    # HTTP to HTTPS redirect router
    main-app-router-redirect:
      rule: "Host(`auth.example.com`)"
      service: next-service
      entryPoints:
        - web
      middlewares:
#        - redirect-to-https

    # Next.js router (handles everything except API and WebSocket paths)
    next-router:
      rule: "Host(`auth.example.com`) && !PathPrefix(`/api/v1`)"
      service: next-service
      entryPoints:
        - websecure
      tls:
        certResolver: letsencrypt

    # API router (handles /api/v1 paths)
    api-router:
      rule: "Host(`auth.example.com`) && PathPrefix(`/api/v1`)"
      service: api-service
      entryPoints:
        - websecure
      tls:
        certResolver: letsencrypt

    # WebSocket router
    ws-router:
      rule: "Host(`auth.example.com`)"
      service: api-service
      entryPoints:
        - websecure
      tls:
        certResolver: letsencrypt

  services:
    next-service:
      loadBalancer:
        servers:
          - url: "http://pangolin:3002"  # Next.js server

    api-service:
      loadBalancer:
        servers:
          - url: "http://pangolin:3000"  # API/WebSocket server

````````````````````

My issue now appears to be when logging in, i've entered my credentials as per the config.yml but i always get this error message and cannot proceed any further.

![image](https://github.com/user-attachments/assets/23434a42-3e9d-4059-a4d4-b2f697888974)

This is in the Pangolin logs;

`````````````````````````````````
2025-02-04T09:24:14.657Z [[33mwarn[39m]: Email SMTP configuration is missing. Emails will not be sent.
2025-02-04T09:24:14.768Z [[32minfo[39m]: Updated orgs with new domain (example.com)
2025-02-04T09:24:14.886Z [[32minfo[39m]: Server admin (admin@example.com) already exists
2025-02-04T09:24:14.891Z [[34mdebug[39m]: Using CORS options {"origin":["https://auth.example.com"],"methods":["GET","POST","PUT","DELETE","PATCH"],"credentials":false}
2025-02-04T09:24:15.477Z [[32minfo[39m]: API server is running on http://localhost:3000
2025-02-04T09:24:15.479Z [[32minfo[39m]: Internal server is running on http://localhost:3001
2025-02-04T09:24:15.693Z [[32minfo[39m]: Next.js server is running on http://localhost:3002
2025-02-04T09:33:01.294Z [[34mdebug[39m]: GET /api/v1/user
2025-02-04T09:33:01.463Z [[34mdebug[39m]: GET /api/v1/user
`````````````````````````````````

I did a fresh install of Pangolin using the installer and the only edits i have made is the commenting out of the middleware redirect and changing the config to debug logs and save them.

Any further help is apprecated.

Thank you again
