### DISCUSSION TITLE
Help setting up services with Traefik on a Pangolin server

### DISCUSSION THREAD

**Discussion by UncleArya** [fosrl/pangolin#168] [Q&A] [answered]
Hello. I was hoping someone might be able to help me figure out where I am going wrong in trying to setup other services with Traefik on my VPS that is also running Pangolin. I have never used Traefik before and I have gone through the documentation and watched some tutorials but none of them are specific to Pangolin and I can't figure out how to get it working. I run most services on my home server which has the Newt connection to my Pangolin VPS server, but I want to run a few services on my VPS as well. I have tried a few example services to attempt figuring out Traefik labels but I am stuck. When I run the containers I get an error in my browser saying it's and invalid security certificate and a self-signed certificate. Proxy and DNS stuff is my weak point with self hosted so I really appreciate any knowledge folks might have to share.

Here is an example docker-compose file that I have been using:
```
name: convertx
services:
  convertx:
    image: c4illin/convertx:v0.10.1
    container_name: convertx
    # ports:
    #   - 3000:3000
    volumes:
      - ./convertx:/app/data
    environment:
      JWT_SECRET: <random string>
      ALLOW_UNAUTHENTICATED: false
      AUTO_DELETE_EVERY_N_HOURS: 24
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.convertx.rule=Host(`convert.pangolin.base.domain`)"
      - "traefik.http.routers.convertx.entrypoints=websecure"
      - "traefik.http.routers.convertx.tls=true"
      - "traefik.http.routers.convertx.tls.certresolver=letsencrypt"
      - "traefik.http.services.convertx.loadbalancer.server.port=3000"
      - "traefik.docker.network=pangolin"
    restart: unless-stopped
    networks:
      - pangolin  # Network I have added to my Gerbil & Pangolin service
networks:
  pangolin:
    name: pangolin
    external: true
```

Do I need to edit something in my Pangolin config? Do I need to manually add DNS records?

Thank you so much to those who may be willing to help!
