### DISCUSSION TITLE
How I got Home Assistant proxied

### DISCUSSION THREAD

**Discussion by FunDeckHermit** [fosrl/pangolin#232] [Show and tell]
Home Assistant isn't the easiest application to proxy. It requires setting some Headers, upgrading connections and writing some config files. Luckily the Headers and connection out of Newt seem to be fine, this just leaves the config.

**Setup:**
Home Assistant Operating System 14.2
Home Assistant Core 2025.2.5
Pangolin v1.0.0-beta.14
Newt 1.0.0-beta.5

First finish initialization of Pangolin and have a working connection to Newt. I can recommend testing the connection by running `python3 -m http.server` somewhere on your local network and have Pangolin point to it. 

To edit the `configuration.yaml` file it is recommended to install the Visual Studio Code Server and editing the file from there. Changes are only propagated after a restart, so make sure to reboot the HA after changes (Developer tools -> Restart -> Restart Home Assistant). 

Newt is probably running in Docker so you also need the Docker IP-address configured as trusted_proxy in Home Assistant. On the Docker host run `docker network inspect newt_default` and find the IPv4Address. Also write down the Docker host IP-address.

Append the `configuration.yaml` file with the following lines.
The specific IP-address and ranges depend on your network. 
```
http:
  use_x_forwarded_for: true
  trusted_proxies:
    - 192.168.48.106  #Docker Host IP
    - 172.18.0.2      #Docker container IP

homeassistant:
  auth_providers:
    - type: homeassistant
    - type: trusted_networks
      trusted_networks:
        - 192.168.0.0/16
```
Then add a Pangolin Resource that proxies to the Home Assistant IP address. Using the hostname didn't work for whatever reason.  
![image](https://github.com/user-attachments/assets/43a0213d-02b1-4673-a306-b85599fb4dcc)
