### DISCUSSION TITLE
Add support for only forwarding specific url paths

### DISCUSSION THREAD

**Discussion by RichyHBM** [fosrl/pangolin#238] [Q&A] [answered]
As it currently stands, If I add a service to pangolin it will forward any and all requests no matter the url path.

With my previous setup using cloudflare + manual traefik setup, I could setup the traefik host rule to only respond to specific url paths as such:

```
  routers:    
    umami:
      rule: "Host(`analytics.domain.co.uk`) && (Path(`/script.js`) || Path(`/api/ingress`))"
      entrypoints:
        - http
      service: umami@file
```

Which would allow me to publicly allow those endpoints, without allowing full access to the web service. 

One option could be to allow a 3rd "custom" option for setting the domain of a resource, which could allow raw traefik rule config to be put in?
