### DISCUSSION TITLE
Crowdsec setup

### DISCUSSION THREAD

**Discussion by asychev** [fosrl/pangolin#303] [General]
Hi!

Couple of notes about crowdsec configuration by installer:
1. Latest `crowdsec-bouncer-traefik-plugin` is [v1.4.1](https://github.com/maxlerebourg/crowdsec-bouncer-traefik-plugin/releases/tag/v1.4.1l) (installer uses v1.3.5)
2. [This](https://github.com/fosrl/pangolin/blob/main/install/config/crowdsec/dynamic_config.yml#L18) does not make sense as Response header, it is a Request header to indicate downstream service that https is used by client:
```
    security-headers:
      headers:
        customResponseHeaders: 
          X-Forwarded-Proto: "https"  # Set forwarded proto to https
```
Hope it helps ;)
