### DISCUSSION TITLE
Help on resource creation. It doesn't work for me.

### DISCUSSION THREAD

**Discussion by LordSpectre** [fosrl/pangolin#313] [Q&A]
Dear community, I installed Pangolin, following the official guide, on racknerd VPS with Ubuntu 24.10. Every containers are up&running (I skip for now the Crowdsec installation). I can reach the Pangoling GUI via mysubdmain: http://tunnel.mysite.com. I configured the site and the newt tunnel, running on my server at home is now UP.
Next I created a resource, with another subdomain. e.g. subdomain.mysite.com (of course I created the A record on my DNS provider) with target 192.168.1.100:80 (the machine where the newt runs). Now what? 

Shouldn't I expect the Traefik configuration to be modified so that it can point to the tunnel?
Instead, when I navigate to https://subdomain.mysite.com/, what I get is a redirect to the Pangolin GUI (which then doesn't work and gives a 404 error). When registering a resource, shouldn't the Traefik configuration also be updated? Am I wrong? Below is the configuration: dynamic_config.yml of Traefik after adding the resource, no trace of it:

```
http:
  middlewares:
    redirect-to-https:
      redirectScheme:
        scheme: https

  routers:
    # HTTP to HTTPS redirect router
    main-app-router-redirect:
      rule: "Host(`tunnel.mysite.com`)"
      service: next-service
      entryPoints:
        - web
      middlewares:
        - redirect-to-https

    # Next.js router (handles everything except API and WebSocket paths)
    next-router:
      rule: "Host(`tunnel.mysite.com`) && !PathPrefix(`/api/v1`)"
      service: next-service
      entryPoints:
        - websecure
      tls:
        certResolver: letsencrypt

    # API router (handles /api/v1 paths)
    api-router:
      rule: "Host(`tunnel.mysite.com`) && PathPrefix(`/api/v1`)"
      service: api-service
      entryPoints:
        - websecure
      tls:
        certResolver: letsencrypt

    # WebSocket router
    ws-router:
      rule: "Host(`tunnel.mysite.com`)"
      service: api-service
      entryPoints:
        - websecure
      tls:
        certResolver: letsencrypt

  services:
    next-service:
      loadBalancer:
        servers:
          - url: "http://pangolin:3002"  # Next.js server

    api-service:
      loadBalancer:
        servers:
          - url: "http://pangolin:3000"  # API/WebSocket server
```

Could someone advice please?
Thank you
Lucas
