### DISCUSSION TITLE
Crowdsec parser/scenario for pangolin itself

### DISCUSSION THREAD

**Discussion by RomRider** [fosrl/pangolin#314] [Show and tell]
Given you're already promoting crowdsec, I thought it would be interesting to add a parser and scenario for pangolin itself.

* Parser:
  ```yaml
  name: fosrl/pangolin
  description: "Parse pangolin access logs"
  filter: "evt.Parsed.program startsWith 'pangolin'"
  #debug: true
  onsuccess: next_stage
  pattern_syntax:
    PANGOLIN_FAILED_LOGIN: '^%{TIMESTAMP_ISO8601:timestamp}.*Username or password incorrect\. Email: %{EMAILADDRESS:user}\. IP: %{IP:source_ip}\.$'
    PANGOLIN_FAILED_2FA: '^%{TIMESTAMP_ISO8601:timestamp}.*Two-factor code incorrect\. Email: %{EMAILADDRESS:user}\. IP: %{IP:source_ip}\.$'
  nodes:
    - grok:
        name: PANGOLIN_FAILED_LOGIN
        apply_on: message
        statics:
          - meta: log_type
            value: pangolin_failed_auth
    - grok:
        name: PANGOLIN_FAILED_2FA
        apply_on: message
        statics:
          - meta: log_type
            value: pangolin_failed_auth
  statics:
      - meta: service
        value: pangolin
      - target: evt.StrTime
        expression: evt.Parsed.timestamp
      - meta: source_ip
        expression: evt.Parsed.source_ip
      - meta: user
        expression: evt.Parsed.user
  ```

* Scenario
  ```yaml
  type: leaky
  name: fosrl/pangolin-bf
  description: "Detect Pangolin bruteforce attacks"
  filter: "evt.Meta.log_type == 'pangolin_failed_auth'"
  leakspeed: 1m
  capacity: 5
  groupby: evt.Meta.source_ip
  blackhole: 5m
  reprocess: true
  labels:
    service: pangolin
    spoofable: 0
    confidence: 3
    classification:
      - attack.T1110
    label: "Pangolin Bruteforce"
    behavior: "http:bruteforce"
    remediation: true
  ```

It requires to mount `config/logs` into the crowdsec container, eg. `/var/log/pangolin`
Update the `acquis.yaml` file with:
```yaml
poll_without_inotify: true
filenames:
  - /var/log/pangolin/pangolin.log
labels:
  type: pangolin
```
Also, you'll need to enable writing log files in the pangolin `config.yaml`:
```yaml
app:
    log_level: "info"
    save_logs: true
    log_failed_attempts: true
```

Ideally, you might want to publish this natively to crowdsec through their repo, if it makes sense. So this is kind of a feature request/solution.
