### DISCUSSION TITLE
Whitelist IP in crowdsec

### DISCUSSION THREAD

**Discussion by manilx** [fosrl/pangolin#358] [Q&A]
How do I whitelist an IP from Crowdsec?
Just got blacklisted out of the blue. And I can’t have that.

**Comment by aszurnasirpal** [comment]
You're not alone. Out of the box - many of us had problems with accessing the Pangolin as all IPs are blocked. 
https://github.com/orgs/fosrl/discussions/328

**Comment by manilx** [comment]
Removed Crowdsec from my config.

**Reply by hhftechnology** [reply]
> Removed Crowdsec from my config.

To solve the issue of CrowdSec banning dynamic IP addresses for you and other users accessing your instance(This applies to any dyanamic ip users), here solution:

### automatic IP Whitelisting for Dynamic Addresses
1. **use the DynDNS IP Whitelister Script**  
   A Python script ([GitHub](https://github.com/philippehmeier/crowdsec-dyndns-ip-whitelister)) automates IP whitelisting for dynamic addresses:
   - Finds your public IP using `ipinfo.io`  
   - updates CrowdSec's `publicIpWhitelist.yaml` if the IP changes  
   - reloads CrowdSec service to apply changes  

   **implementation steps**:
   ```bash
   # Install prerequisites
   sudo cscli parsers install crowdsecurity/whitelists
   sudo apt install python3 python3-requests

   # Configure cron job (run every 5 minutes)
   */5 * * * * root python3 /path/to/publicIpWhitelister.py
   ```

2. **Multi-User Solution with Dynamic DNS**  
   for other users with dynamic IPs:
   - Each user should set up a free DDNS service (e.g., DuckDNS, No-IP)  
   - Create whitelist entries using CrowdSec's `LookupHost` function:
     ```yaml
     # /etc/crowdsec/parsers/s02-enrich/dynamic_whitelists.yaml
     name: dynamic-whitelists
     description: "Whitelist DDNS hostnames"
     whitelist:
       reason: "Authorized users"
       expression:
         - evt.Overflow.Alert.Source.IP in LookupHost("user1.ddns.net")
         - evt.Overflow.Alert.Source.IP in LookupHost("user2.ddns.net")
     ```
   - Reload configuration:  
     ```bash
     sudo docker restart crowdsec
     ```

### Points to be noted. 
- **Existing Bans**: Remove current IP bans manually:  
  ```bash
  sudo docker  exec crowdsec cscli decisions delete --ip 
  ```
- **Verification**:  
  Check active whitelists with:
  ```bash
  docker  exec crowdsec cscli parsers list | grep whitelist
  ```
