### DISCUSSION TITLE
How to remove Crowdsec?

### DISCUSSION THREAD

**Discussion by maikbasel** [fosrl/pangolin#360] [Q&A] [answered]
I used the installer script to automatically install and configure Crowdsec in my Pangolin instance. 

Now I want to get rid of it, since Crowdsec will ban my own IP address every time I work with a certain module in the FoundryVTT instance behind my Pangolin. Whitelisting my IP is not an option as it will be changed by my internet provider regularly. I also have other user's that will have the same problem

Is there a way to remove Crowdsec without having to entirely remove Pangolin and then set it up again? I really don't want to repeat the whole installation an configuration process again.

Any help would be appreciated, thanks.

**Comment by miloschwartz** [comment, marked as answer]
I think the easiest way to remove it would be to remove it from the docker-compose file, then remove it from Traefik by removing the middleware definition and reference in the `traefik_config.yml` and `dynamic_config.yml`.

**Reply by maikbasel** [reply]
This works thanks a lot. The answer of @hhftechnology  might prove useful in the future as well.

**Comment by hhftechnology** [comment]
> Now I want to get rid of it, since Crowdsec will ban my own IP address every time I work with a certain module in the FoundryVTT instance behind my Pangolin. Whitelisting my IP is not an option as it will be changed by my internet provider regularly. I also have other user's that will have the same problem

To solve the issue of CrowdSec banning dynamic IP addresses for you and other users accessing your FoundryVTT instance(This applies to any dyanamic ip users), here solution:

### automatic IP Whitelisting for Dynamic Addresses
1. **use the DynDNS IP Whitelister Script**  
   A Python script ([GitHub](https://github.com/philippehmeier/crowdsec-dyndns-ip-whitelister)) automates IP whitelisting for dynamic addresses:
   - Finds your public IP using `ipinfo.io`  
   - updates CrowdSec's `publicIpWhitelist.yaml` if the IP changes  
   - reloads CrowdSec service to apply changes  

   **implementation steps**:
   ```bash
   # Install prerequisites
   sudo cscli parsers install crowdsecurity/whitelists
   sudo apt install python3 python3-requests

   # Configure cron job (run every 5 minutes)
   */5 * * * * root python3 /path/to/publicIpWhitelister.py
   ```

2. **Multi-User Solution with Dynamic DNS**  
   for other users with dynamic IPs:
   - Each user should set up a free DDNS service (e.g., DuckDNS, No-IP)  
   - Create whitelist entries using CrowdSec's `LookupHost` function:
     ```yaml
     # /etc/crowdsec/parsers/s02-enrich/dynamic_whitelists.yaml
     name: dynamic-whitelists
     description: "Whitelist DDNS hostnames"
     whitelist:
       reason: "Authorized users"
       expression:
         - evt.Overflow.Alert.Source.IP in LookupHost("user1.ddns.net")
         - evt.Overflow.Alert.Source.IP in LookupHost("user2.ddns.net")
     ```
   - Reload configuration:  
     ```bash
     sudo docker restart crowdsec
     ```

### Points to be noted. 
- **Existing Bans**: Remove current IP bans manually:  
  ```bash
  sudo docker  exec crowdsec cscli decisions delete --ip 
  ```
- **Verification**:  
  Check active whitelists with:
  ```bash
  docker  exec crowdsec cscli parsers list | grep whitelist
  ```
