### DISCUSSION TITLE
How to install the Fail2Ban properly

### DISCUSSION THREAD

**Discussion by LeonvanHeerden** [fosrl/pangolin#372] [Q&A]
I am trying to install the Fail2Ban plugin on the Pangolin Docker instance. I am not really familiar with Traefik and require some help to get the initial setup working. 

I am trying to follow in [the instruction on the Traefik page](https://plugins.traefik.io/plugins/628c9ebcffc0cd18356a979f/fail2-ban), but there is some config that I am not sure where it goes. 

Done so far:
Edited dynamic Traefik file `./docker/pangolin/config/traefik/dynamic_config.yml` and added this under the existing http middleware section:
```
http:
  middlewares:
    redirect-to-https:
      redirectScheme:
        scheme: https
    my-fail2ban:
      plugin:
        fail2ban:
          allowlist:
             ip: ::1,127.0.0.1
          denylist:
             ip: 192.168.0.0/24
          rules:
            bantime: 3h
            enabled: "true"
            findtime: 10m
            maxretry: "4"
            statuscode: 400,401,403-499
```

Edited the Traefik Static config file `./docker/pangolin/config/traefik/traefik_config.yml` and added the below. 
```
experimental:
  plugins:
    badger:
      moduleName: github.com/fosrl/badger
      version: v1.0.0
    fail2ban:
      moduleName: "github.com/tomMoulard/fail2ban"
      version: "v0.8.3"
```

Then I restarted the docker container. Now the config page refers to more changes, but it doesn't indicate where these changes are to be made.  I have not worked with Traefik enough to know what next. 
Anyone know where the last bit of middleware config should go?

From the fail2ban Traefik page:

# Middleware
After installing the plugin, it can be configured through a Middleware, e.g.:
```
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: fail2ban-test
spec:
  plugin:
    fail2ban:
      logLevel: DEBUG
      denylist:
        ip: 127.0.0.1
```
Add the middleware to an ingressroute
```
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: simplecrd
  namespace: default
spec:
  entryPoints:
    - web
  routes:
  - match: Host(`fail2ban.localhost`)
    kind: Rule
    middlewares:
    - name: fail2ban-test
    services:
    ...
```
