### DISCUSSION TITLE
HSTS & http-to-https-redirect

### DISCUSSION THREAD

**Discussion by MK796** [fosrl/pangolin#382] [Q&A]
Hello all,

I have the problem that HSTS headers are only sent with pangolins base domain and the first subdomain I have ever created.
Also HTTPS redirect is sometimes working sometimes it's not. 

I'm at the end with my troubleshooting capabilities... 
maybe someone could help me understanding where to look? 
maybe a Bug?

All versions current!!

Thank you very much :)

**Comment by MK796** [comment]
Hello I have found out how to set the neccessary headers for the base domain
Its functioning like intended, but not for the subdomains.
Please see my code below:


```
    redirect-to-https:
      redirectScheme:
        scheme: https
    
    security-headers:
      headers:
        contentTypeNosniff: true
        customFrameOptionsValue: SAMEORIGIN
        customResponseHeaders:
          Server: ""
          X-Forwarded-Proto: https
          X-Powered-By: ""
        forceSTSHeader: true
        hostsProxyHeaders:
          - X-Forwarded-Host
        referrerPolicy: strict-origin-when-cross-origin
        sslProxyHeaders:
          X-Forwarded-Proto: https
        stsIncludeSubdomains: true
        stsPreload: true
        stsSeconds: 31536000
  
  routers:
    main-app-router-redirect:
      rule: "Host(`ingress.example.com`)"
      service: next-service
      entryPoints:
        - web
      middlewares:
        - redirect-to-https
    
    next-router:
      rule: "Host(`ingress.example.com`) && !PathPrefix(`/api/v1`)"
      service: next-service      
      entryPoints:
        - websecure      
      middlewares:
        - security-headers
      tls:
        certResolver: letsencrypt
        domains:
          - main: "example.com"
            sans:
              - "*.example.com"
```

**Reply by miloschwartz** [reply]
You can apply the security headers middleware to the websecure entrypoint to apply to all resources. That should make it apply to your subdomains because right now it's just applied to the main site based on the snippet you sent.

**Reply by MK796** [reply]
Hello Milo,

Thank you for your answer! 

In which file? 

Cheers
Marvin

**Reply by miloschwartz** [reply]
I think you can keep the security-headers middleware defined in the dynamic config and then reference the middleware under the websecure middleware. More info in the Traefik docs here: https://doc.traefik.io/traefik/routing/entrypoints/#middlewares

**Reply by MK796** [reply]
Hello Milo,

Thank you for that helpful hint!

FIRST:

with this configuration HSTS headers are send with each subdomain and the base domain.
But HTTPS redirect is not working as expected...

I have tested HTTPS redirect like with this configuration:

 1. traefik_config.yml

```
accessLog:
  bufferingSize: 100
  fields:
    defaultMode: drop
    headers:
      defaultMode: drop
      names:
        Authorization: redact
        Content-Type: keep
        Cookie: redact
        User-Agent: keep
        X-Forwarded-For: keep
        X-Forwarded-Proto: keep
        X-Real-Ip: keep
    names:
      ClientAddr: keep
      ClientHost: keep
      DownstreamContentSize: keep
      DownstreamStatus: keep
      Duration: keep
      RequestMethod: keep
      RequestPath: keep
      RequestProtocol: keep
      RetryAttempts: keep
      ServiceName: keep
      StartUTC: keep
      TLSCipher: keep
      TLSVersion: keep
  filePath: /var/log/traefik/access.log
  filters:
    minDuration: 100ms
    retryAttempts: true
    statusCodes:
      - 200-299
      - 400-499
      - 500-599
  format: json

api:
  dashboard: true
  insecure: true

certificatesResolvers:
  letsencrypt:
    acme:
      caServer: https://acme-v02.api.letsencrypt.org/directory
      dnsChallenge:
        provider: cloudflare
        resolvers:
          - 1.1.1.1:53
      email: mail@address.com
      httpChallenge:
        entryPoint: web
      storage: /letsencrypt/acme.json

entryPoints:
  web:
    address: ':80'
    http:
      middlewares:
        - redirect-to-https@file
  websecure:
    address: ':443'
    http:
      middlewares:
        - crowdsec@file
        - security-headers@file
      tls:
        certResolver: letsencrypt
    transport:
      respondingTimeouts:
        readTimeout: 30m

experimental:
  plugins:
    badger:
      moduleName: github.com/fosrl/badger
      version: v1.0.0
    crowdsec:
      moduleName: github.com/maxlerebourg/crowdsec-bouncer-traefik-plugin
      version: v1.3.5

log:
  format: json
  level: INFO
providers:
  file:
    filename: /etc/traefik/dynamic_config.yml
  http:
    endpoint: http://pangolin:3001/api/v1/traefik-config
    pollInterval: 5s

serversTransport:
  insecureSkipVerify: true
```

2. dynamic_config.yml

```
http:
  middlewares:
    crowdsec:
      plugin:
        crowdsec:
          clientTrustedIPs:
            - 10.0.0.0/8
            - 172.16.0.0/12
            - 192.168.0.0/16
            - 100.89.137.0/20
          crowdsecAppsecEnabled: true
          crowdsecAppsecFailureBlock: true
          crowdsecAppsecHost: crowdsec:7422
          crowdsecAppsecUnreachableBlock: true
          crowdsecLapiHost: crowdsec:8080
          crowdsecLapiKey: Key
          crowdsecLapiScheme: http
          crowdsecMode: live
          defaultDecisionSeconds: 15
          enabled: true
          forwardedHeadersTrustedIPs:
            - 0.0.0.0/0
          httpTimeoutSeconds: 10
          logLevel: INFO
          updateIntervalSeconds: 15
          updateMaxFailure: 0
    default-whitelist:
      ipWhiteList:
        sourceRange:
          - 10.0.0.0/8
          - 192.168.0.0/16
          - 172.16.0.0/12
    
    redirect-to-https:
      redirectScheme:
        scheme: https
    
    security-headers:
      headers:
        contentTypeNosniff: true
        customFrameOptionsValue: SAMEORIGIN
        customResponseHeaders:
          Server: ""
          X-Forwarded-Proto: https
          X-Powered-By: ""
        forceSTSHeader: true
        hostsProxyHeaders:
          - X-Forwarded-Host
        referrerPolicy: strict-origin-when-cross-origin
        sslProxyHeaders:
          X-Forwarded-Proto: https
        stsIncludeSubdomains: true
        stsPreload: true
        stsSeconds: 31536000
  
  routers:
    main-app-router-redirect:
      rule: "Host(`my.subdomain.net`)" 
      service: next-service
      entryPoints:
        - web
      #middlewares:
        #- redirect-to-https
    
    next-router:
      rule: "Host(`my.subdomain.net`) && !PathPrefix(`/api/v1`)"
      service: next-service      
      entryPoints:
        - websecure      
      #middlewares:
        #- security-headers
      tls:
        certResolver: letsencrypt
        domains:
          - main: "subdomain.net"
            sans:
              - "*.subdomain.net"
    
    api-router:     
      rule: "Host(`my.subdomain.net`) && PathPrefix(`/api/v1`)"
      service: api-service
      entryPoints:
        - websecure      
      #middlewares:
        #- security-headers
      tls:
        certResolver: letsencrypt
   
    ws-router:
      rule: "Host(`my.subdomain.net`)"
      service: api-service
      entryPoints:
        - websecure      
      #middlewares:
        #- security-headers      
      tls:
        certResolver: letsencrypt
  
  services:
    next-service:
      loadBalancer:
        servers:
          - url: "http://pangolin:3002"
    
    api-service:
      loadBalancer:
        servers:
          - url: "http://pangolin:3000"
```


But when I'm testing it with:

```
curl -4 -I http://my.subdomain.net   
OR    
curl -6 -I http://my.subdomain.net
```

I get the output:

```
curl -4 -I http://my.subdomain.net
HTTP/1.1 200 OK
Server: nginx/1.24.0 (Ubuntu)
Date: Sun, 23 Mar 2025 13:54:07 GMT
Content-Type: text/html
Content-Length: 615
Last-Modified: Tue, 22 Oct 2024 12:24:22 GMT
Connection: keep-alive
ETag: "67179976-267"
Accept-Ranges: bytes

curl -4 -I http://my.subdomain.net
HTTP/1.1 200 OK
Server: nginx/1.24.0 (Ubuntu)
Date: Sun, 23 Mar 2025 13:54:07 GMT
Content-Type: text/html
Content-Length: 615
Last-Modified: Tue, 22 Oct 2024 12:24:12 GMT
Connection: keep-alive
ETag: "6717996c-267"
Accept-Ranges: bytes

curl -4 -I http://my.subdomain.net
HTTP/1.1 307 Temporary Redirect
Location: https://my.subdomain.net/
Date: Sun, 23 Mar 2025 13:54:08 GMT
Content-Length: 18

curl -6 -I http://my.subdomain.net
HTTP/1.1 200 OK
Server: nginx/1.24.0 (Ubuntu)
Date: Sun, 23 Mar 2025 13:54:10 GMT
Content-Type: text/html
Content-Length: 615
Last-Modified: Tue, 22 Oct 2024 12:24:22 GMT
Connection: keep-alive
ETag: "67179976-267"
Accept-Ranges: bytes

curl -6 -I http://my.subdomain.net
HTTP/1.1 200 OK
Server: nginx/1.24.0 (Ubuntu)
Date: Sun, 23 Mar 2025 13:54:12 GMT
Content-Type: text/html
Content-Length: 615
Last-Modified: Tue, 22 Oct 2024 12:24:12 GMT
Connection: keep-alive
ETag: "6717996c-267"
Accept-Ranges: bytes

curl -6 -I http://my.subdomain.net
HTTP/1.1 307 Temporary Redirect
Location: https://my.subdomain.net/
Date: Sun, 23 Mar 2025 13:54:12 GMT
Content-Length: 18
```

so you can see that the redirect is performed every third time when im executing the command...
