### DISCUSSION TITLE
[Feature Request]  Update Traefik dynamic config to use resource name instead of resource number

### DISCUSSION THREAD

**Discussion by just5ky** [fosrl/pangolin#430] [Feature Requests]
## Issue
- Currently, Pangolins generated Traefik dynamic config has object name as `4-router@http`, which makes it difficult to know where the web-traffic is flowing.

- Looking at the pangolins URL path, in this case 4 turns out to be Jellyfin
`https://pangolin.domain/organization_name/settings/resources/4/connectivity`

`IP - - [29/Mar/2025:16:40:26 +0000] "GET /i/?a=normal&get=c_9 HTTP/2.0" 200 67834 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/134.0.0.0 Safari/537.36" 20393 "4-router@http" "http://100.89.128.4:41168" 1147ms`

![Image](https://github.com/user-attachments/assets/b1752c5b-39b7-42d8-8ead-691db52ea7bd)

## Proposed Solution 
- Modify/Update the dynamic config generated by Pangolin to use resource name instead of resource number.
> **_NOTE:_** Need to sanitize the name, since pangolin resource names can have spaces and special characters that may break dynamic config

## References
https://doc.traefik.io/traefik/providers/overview/#provider-namespace
https://doc.traefik.io/traefik/providers/http/

---
>  Thanks for making this awesome software. Loving it!

**Comment by miloschwartz** [comment]
Resource name is not unique, but this could work if we generate a unique key, like: `<name>-<id>`

**Reply by just5ky** [reply]
Yeah, and also need to sanitize it too, incase someone puts `@` i the name, that will break the config

**Reply by hhftechnology** [reply]
@just5ky if you want to  `docker exec pangolin curl http://localhost:3001/api/v1/traefik-config | jq` till developer figure out a way. it a cheat code to know what goes where.

**Reply by just5ky** [reply]
You are right, nice little cheat code. Thanks

**Comment by miloschwartz** [comment]
Converting this to a feature request in discussions.

**Comment by OddMagnet** [comment]
Would love to see this implemented as well. 
Are you open for PR's for this kind of change?
I'm not well versed in Typescript, but if nobody else wants to attempt it I might take a look at it the next time I find some free time.

**Comment by oschwartz10612** [comment]
Sure @OddMagnet go for it! Please create an issue or a draft PR first 
and I can assign it to you.

Make sure to include the resource ID in the name because each router has 
to be globally unqiue and the only globally unique ID is the number 
right now! :}

**Reply by OddMagnet** [reply]
Found some time and tried to set it up, but I'm already struggling with that 😭 

I'm using MacOS, so I had to create a custom bridge network for the containers to talk to each other.
After starting pangolin I connected it to the network.

For Gerbil I used the default compose file, only setting `remoteConfig` to `http://dev_pangolin:3001/api/v1/`

I connected Gerbil to the network as well and it was able to connect to Pangolin. I didn't manage to connect Newt however, this is the compose file I used for it:

```
networks:
  default: # A network shared only by newt and whoami
    external: false
    name: newtwork
  localnet: # The network that's already being used by Pangolin and Gerbil
    external: true
    name: localnet

services:
  newt:
    image: fosrl/newt
    container_name: newt
    restart: unless-stopped
    environment:
      - PANGOLIN_ENDPOINT=http://dev_pangolin:3001
      - NEWT_ID=...
      - NEWT_SECRET=...
    networks:
      - default
      - localnet

  whoami:
    container_name: whoami
    image: traefik/whoami
    restart: unless-stopped
```

This however only gets me 404 errors.
