### DISCUSSION TITLE
Setup Pangolin with exisiting traefik instance

### DISCUSSION THREAD

**Discussion by Checker8763** [fosrl/pangolin#457] [Q&A]
Hey to everybody interested in the topic or trying to achieve the same thing.

Setup:
I have an existing server setup with docker and traefik and other services.

- Pangolin is setup with docker (-compose)
- Pangolin can talk to gerbil.
- Pangolin can push configuration to traefik via HTTP provider
- Gerbil is accessible and can accept newt connections.
- Traefik has the badger plugin installed (and configured via pangolins HTTP provider)

pangolin is full functional and accessible but my traefik instance is not able to route the VPN IPs of gerbil to the gerbil container.

And that seems to be not easily accomplished...

Any help hint or tips appreciated!

**Comment by hhftechnology** [comment]
> Hey to everybody interested in the topic or trying to achieve the same thing.
> 
> Setup: I have an existing server setup with docker and traefik and other services.
> 
> * Pangolin is setup with docker (-compose)
> * Pangolin can talk to gerbil.
> * Pangolin can push configuration to traefik via HTTP provider
> * Gerbil is accessible and can accept newt connections.
> * Traefik has the badger plugin installed (and configured via pangolins HTTP provider)
> 
> pangolin is full functional and accessible but my traefik instance is not able to route the VPN IPs of gerbil to the gerbil container.
> 
> And that seems to be not easily accomplished...
> 
> Any help hint or tips appreciated!

traefik should exit through gerbil if you want a tunnel.

```yaml
  gerbil:
    image: fosrl/gerbil:1.0.0
    container_name: gerbil
    restart: unless-stopped
    depends_on:
      pangolin:
        condition: service_healthy
    command:
      - --reachableAt=http://gerbil:3003
      - --generateAndSaveKeyTo=/var/config/key
      - --remoteConfig=http://pangolin:3001/api/v1/gerbil/get-config
      - --reportBandwidthTo=http://pangolin:3001/api/v1/gerbil/receive-bandwidth
    volumes:
      - ./config/:/var/config
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    ports:
      - 51820:51820/udp
      - 443:443 # Port for traefik because of the network_mode
      - 80:80 # Port for traefik because of the network_mode

  traefik:
    image: traefik:v3.3.3
    container_name: traefik
    restart: unless-stopped

    network_mode: service:gerbil # Ports appear on the gerbil service

    depends_on:
      pangolin:
        condition: service_healthy
    command:
      - --configFile=/etc/traefik/traefik_config.yml
    volumes:
      - ./config/traefik:/etc/traefik:ro # Volume to store the Traefik configuration
      - ./config/letsencrypt:/letsencrypt # Volume to store the Let's Encrypt certificates
      - ./config/traefik/logs:/var/log/traefik # Volume to store Traefik logs

```
