### DISCUSSION TITLE
Multiple DNS API Tokens

### DISCUSSION THREAD

**Discussion by phatlix** [fosrl/pangolin#487] [Q&A] [answered]
Hello All,

I have done some digging into this and am not finding any documentation or others asking similar questions.  I apologize if I missed it and if I can be pointed in the correct direction would be awesome!  I just have a feeling it doesn't exist though.

I am trying to setup a couple domains, each with their own working SSL certs (wildcard certs).  My issue is that the domains exist in different Cloudflare accounts (if cloudflare would freaking allow domain transfers to happen internally, I wouldn't be here).  

Is it possible to not only generate domains within the `config.yml` : 
```
domains:
  domain01:
    base_domain: domain01.tld
    cert_resolver: letsencrypt
    prefer_wildcard_cert: true
  domain02:
    base_domain: domain02.tld
    cert_resolver: letsencrypt
    prefer_wildcard_cert: true
```

But to also identify multiple API tokens within the `docker-compose.yml` : 
```
environment:
  CLOUDFLARE_DNS_API_TOKEN: "${CF_API_TOKEN_DOMAIN01}"
  CLOUDFLARE_DNS_API_TOKEN2: "${CF_API_TOKEN_DOMAIN02}"
```

I understand that there would be more involved inside the traefik and dynamic configs, but that is what I am having trouble locating... a way to properly set this up.  And that is of course, if it's even possible.

I appreciate your time and feedback!  Thank you!

**Comment by Lokowitz** [comment, marked as answer]
Hi @phatlix,

i just had a look into the traefik [documentation ](https://doc.traefik.io/traefik/https/acme/) and found this:

>### Multiple DNS Challenge 
>Multiple DNS challenge provider are not supported with Traefik, but you can use CNAME to handle that. For example, if you have example.org (account foo) and example.com (account bar) you can create a CNAME on example.org called _acme-challenge.example.org pointing to challenge.example.com. This way, you can obtain certificates for example.org with the bar account.

Hope this helps :)

**Reply by phatlix** [reply]
Hi @Lokowitz,

Thank you for that.  I have been going through the traefik documentation as well, and had noticed that little blurb.  I am trying to wrap my head around how that would actually work, or how a CNAME entry in one account gives permission to generate certs to another account.  Crazy.  Scary kinda.

But!  I love magic!  So I am gunna see what happens. :)

Thank you for responding, and posting your findings.  Very much appreciated!

**Reply by phatlix** [reply]
Also while going through the traefik docs, they explain setting up multiple routers.  So I would assume for instance something like this : 
```
    router-dom01:
      rule: "Host(`domain01.tld`) && !PathPrefix(`/api/v1`)"
      service: next-service
      entryPoints:
        - websecure
      tls:
        certResolver: letsencrypt
        domains:
          - main: "domain01.tld"
            sans:
              - "*.domain01.tld"

    router-dom02:
      rule: "Host(`domain02.tld`) && !PathPrefix(`/api/v1`)"
      service: next-service
      entryPoints:
        - websecure
      tls:
        certResolver: letsencrypt
        domains:
          - main: "domain02.tld"
            sans:
              - "*.domain02.tld"
```

But it still leaves me with questions.
 - do I still use the `PathPrefix`?
 - can I use the same `next-service` and will the Next.js know how to handle these new entries?
 - do I need to create new entry points?
 - oh and this...

I'm still gunna go try the CNAME method (because, magic is fun), I just don't have a lot of traefik experience and if working this out gives me a better understanding of all of it, well,  I'll be better for it later. ;)

**Reply by phatlix** [reply]
Just to report my test and findings...  the CNAME option works.  Now I need to dig into LetsEncrypt and know "why" that works.  Crazy!

For the sake of brevity, here is what was done;

- Pangolin was setup with `domain01.tld` without a wildcard DNS entry.  Mainly to act as a "admin" account (if you will).
- Created a new CNAME entry on `domain02.tld` which is in a different Cloudflare account.
![image](https://github.com/user-attachments/assets/69800902-e1e0-4fa5-bb7b-f076f24b8e74)
- Made the following adjustments to two config files:
```
# pangolin/config/config.yml

domains:
  domain01:
    base_domain: domain01.tld
    cert_resolver: letsencrypt
    prefer_wildcard_cert: false
  domain02:
    base_domain: domain02.tld
    cert_resolver: letsencrypt
    prefer_wildcard_cert: true


# pangolin/config/traefik/dynamic_config.yml

    next-router:
      rule: "Host(`domain01.tld`) && !PathPrefix(`/api/v1`)"
      service: next-service
      entryPoints:
        - websecure
      tls:
        certResolver: letsencrypt
        domains:
          - main: "domain01.tld"
          - main: "domain02.tld"
            sans:
              - "*.domain02.tld"

```

`docker compose down`
`docker compose up -d`

I now have certs created for both domains, and am now able to create resources with valid SSL on `domain02.tld`.

Nice! 🤘
