### DISCUSSION TITLE
How to add a local wordpress resource?

### DISCUSSION THREAD

**Discussion by juxeii** [fosrl/pangolin#539] [Q&A] [answered]
Hi,

I am really a noob and totally new to `pangolin `:)
I would like to host a wordpress site on my VPS. The has been working with cloudflare tunnel so far, but now I wanted to move it to the VPS.
The site was hosted in a docker container. I just made some adaptions for paths and stuff:

```
version: '3.8'

services:
  wordpress:
    image: wordpress:latest
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    ports:
      - 7380:80
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: example_user
      WORDPRESS_DB_PASSWORD: example_pass
      WORDPRESS_DB_NAME: example
      TZ: Europe/Berlin
    volumes:
      - /home/ubuntu/docker/example/public_html:/var/www/html
    labels:
      - traefik.enable=true
      - traefik.http.routers.example.entrypoints=http
      - traefik.http.routers.example.rule=Host(`example.example.org`)
      - traefik.http.routers.example-secure.entrypoints=https

      - traefik.http.routers.example-secure.rule=Host(`example.example.org`)
      - traefik.http.routers.example-secure.tls=true
      - traefik.http.routers.example-secure.service=example
      - traefik.http.services.example.loadbalancer.server.port=80
      - traefik.docker.network=dmz
    networks:
      - dmz
      - default

  db:
    image: mariadb:11.3.2
    container_name: example-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: example
      MYSQL_USER: example_user
      MYSQL_PASSWORD: example_pass
      MYSQL_RANDOM_ROOT_PASSWORD: '1'
    volumes:
      - db:/var/lib/mysql
    networks:
      - default

volumes:
  db:
  
networks:
  dmz:
    external: true
```

Next I created a new local site in `pangolin`:
![image](https://github.com/user-attachments/assets/a4d97535-c13b-4dc8-94a2-71c595982810)

But I have no idea which ip address I have to put here.
I have tried
* The VPS local one 10.0.0.214
* The public ip
* The docker ip

But I always get `Bad Gateway`. I guess I have fundamental misunderstanding of how local resources are supposed to work.
`Pangolin `and `traefik `run on the same docker network I guess, since I have used the installer script. 

In this [article](https://noted.lol/pangolin-local/) it is described how local resources work. But there I see a local portainer installation. I only could install `portainer `and reach it with public ip.

Any help much appreciated, thanks.
