### DISCUSSION TITLE
ERR Cannot retrieve the ACME challenge for

### DISCUSSION THREAD

**Discussion by juxeii** [fosrl/pangolin#608] [Q&A]
Hi,

I have lots of these errors logs in `traefik`:

`ERR Cannot retrieve the ACME challenge for ...`

See attachment for complete log file.
[traefik.txt](https://github.com/user-attachments/files/19928475/traefik.txt)

`traefik_config.yml`:
```
accessLog:
  bufferingSize: 100
  fields:
    defaultMode: drop
    headers:
      defaultMode: drop
      names:
        Authorization: redact
        Content-Type: keep
        Cookie: redact
        User-Agent: keep
        X-Forwarded-For: keep
        X-Forwarded-Proto: keep
        X-Real-Ip: keep
    names:
      ClientAddr: keep
      ClientHost: keep
      DownstreamContentSize: keep
      DownstreamStatus: keep
      Duration: keep
      RequestMethod: keep
      RequestPath: keep
      RequestProtocol: keep
      RetryAttempts: keep
      ServiceName: keep
      StartUTC: keep
      TLSCipher: keep
      TLSVersion: keep
  filePath: /var/log/traefik/access.log
  filters:
    minDuration: 100ms
    retryAttempts: true
    statusCodes:
      - 200-299
      - 400-499
      - 500-599
  format: json
api:
  dashboard: true
  insecure: true
certificatesResolvers:
  letsencrypt:
    acme:
      caServer: https://acme-v02.api.letsencrypt.org/directory
      email: someemail@gmail.com
      httpChallenge:
        entryPoint: web
      storage: /letsencrypt/acme.json
entryPoints:
  web:
    address: :80
  websecure:
    address: :443
    http:
      middlewares:
        - geoblock@file
        - crowdsec@file
      tls:
        certResolver: letsencrypt
    transport:
      respondingTimeouts:
        readTimeout: 30m
experimental:
  plugins:
    badger:
      moduleName: github.com/fosrl/badger
      version: v1.1.0
    crowdsec:
      moduleName: github.com/maxlerebourg/crowdsec-bouncer-traefik-plugin
      version: v1.3.5
    geoblock:
      moduleName: github.com/PascalMinder/geoblock
      version: v0.3.2
log:
  format: json
  level: INFO
providers:
  file:
    filename: /etc/traefik/dynamic_config.yml
  http:
    endpoint: http://pangolin:3001/api/v1/traefik-config
    pollInterval: 5s
serversTransport:
  insecureSkipVerify: true
```
`dynamic_config.yml` is also attached.
[dynamic_config.txt](https://github.com/user-attachments/files/19928508/dynamic_config.txt)

There are two domains involved here: `example.org` and `example2.com`.
Both of which are associated with a local resource. They are not tunneled.
Could that be the reason?

On the other hand, I have two more subdomains under `example2.com`, which are also local but do not show up as errors in `traefik`.
