### DISCUSSION TITLE
Possible slow memory leak / underspec'd virtual machine for Pangolin

### DISCUSSION THREAD

**Discussion by MykalMachon** [fosrl/pangolin#613] [Q&A] [answered]
Hey all, 
I love Pangolin but have been running into some issues with running out of RAM on my primary VM. 

## My setup 
- I have pangolin deployed on a 2-core CPU, 2 GB RAM Ubuntu Server VM with 100GB of persistent disk space. 
- I deployed it via the installer on the site following all the steps recommended there. 
- On a fresh start everything runs great with `pangolin`, `newt`, `traefik`, and `crowdsec`. 
- The only other thing I have installed on the host is fail2ban.
- On a fresh start, everything sits around 30% RAM usage and 5% CPU usage. 

## My issues 
every 14-21 days the RAM seems to slowly climb from 30% usage to 75% usage. The majority of the ram seems to be taken up by both the `fosrl/pangolin` and `fosrl/gerbil` containers. 

![image](https://github.com/user-attachments/assets/408afe52-de81-43f6-875a-9b107aa412c4)

Once I hit 75% usage, without fail, I start receiving OOM notices in the docker logs and the host pins itself at 100% CPU usage and becomes unresponsive. Sometimes it recovers itself after 20 minutes and the containers restart. Other times I have to hard reset my VM. 

## My questions 
- Does Pangolin just need more than 2GB of memory to run well long term? Are there recommended host specs I missed somewhere? 
- Has anyone else had issues like this; if so where you able to resolve it? any pointers on settings that could help resolve this would be awesome.
- Is this a memory leak? or have I just misconfigured something?

**Comment by TuncTaylan** [comment]
With the next release there will be a fix for some aspects. Until then check out this discussion: https://github.com/fosrl/pangolin/issues/436#issuecomment-2797924344
I’m running the stack with crowdsec on oracle free tier with 1/8 vCPU core and 1GB RAM.

**Reply by MykalMachon** [reply]
I don't know if this is related; I am not seeing issues with disk size, I'm seeing an issue with RAM usage over time. 
Was this something you were experiencing issues with until you made the change referenced in #436 ? The thread doesn't seem to mention that problem.

**Reply by TuncTaylan** [reply]
Yes, I was referring to RAM issues or rather oom’ed traefik, make sure the configs are set as described.

**Reply by MykalMachon** [reply]
It looks like your changes were merged in so I assume I should be good to just upgrade pangolin then check the settings hey?

**Reply by MykalMachon** [reply]
@TuncTaylan I just implemented this and restarted; I will monitor over the next week and check back here with results.
Finger's crossed that this is the solve I've needed! might even be able to spec down my VPS and save some cash!
Thank you!

**Reply by TuncTaylan** [reply]
Any update, @MykalMachon ?

**Reply by MykalMachon** [reply]
Yeah, @TuncTaylan I'll update in detail tomorrow but I'm still seeing memory balloon up to 80-90% and need to restart. 

Unfortunately the fix didn't seem to solve my issue but I definitely think it's something to do with the traefik and crowdsec integration.

**Reply by TuncTaylan** [reply]
Please post all of your configs as well.

**Reply by MykalMachon** [reply]
Thanks for asking for a follow up @TuncTaylan,
I think I've sorted out my issue but fingers crossed 🤞🏻 I'll keep monitoring over the next few days.

## A fix, and a new issue

Your recommendation actually fixed my issues with Traefik/Pangolin taking up lots of RAM, and OOMing, now it's the crowdsec service taking up all the RAM and causing the same issue where my host just runs out of RAM and crashes.

### Docker stats output 

Here was my docker stats output before the changes 

```bash
CONTAINER ID   NAME       CPU %     MEM USAGE / LIMIT     MEM %     NET I/O           BLOCK I/O         PIDS
0582af4781ca   pangolin   0.34%     180.6MiB / 1.922GiB   9.18%     339MB / 1.78GB    83.5MB / 2.33GB   22
c3f53591c5f4   traefik    1.49%     63.15MiB / 1.922GiB   3.21%     78.7GB / 72.6GB   181MB / 326MB     8
837f2ff2fe01   gerbil     0.00%     4.676MiB / 1.922GiB   0.24%     78.7GB / 72.6GB   19.1MB / 0B       5
b5442984a3f7   crowdsec   0.47%     863.3MiB / 1.922GiB   43.86%    550MB / 366MB     467MB / 3.61GB    49
```

## Sorting out the RAM issues with the `crowdsec` service

I did some reading and found a few others having issues with crowdsec and pangolin.
One of those threads (that I cannot for the life of me find again) mentioned that crowdsec's Prometheus instance may be the one increasing in RAM.
I guess Prometheus stores more and more info as crowdsec accumulates more and more logs. 

### What I'm trying 

I edited `config/crowdsec/user.yaml` and made the following changes: 

```yaml
common:
  daemonize: false
  log_media: stdout
  log_level: info
  log_dir: /var/log/
config_paths:
  config_dir: /etc/crowdsec/
  data_dir: /var/lib/crowdsec/data
  #simulation_path: /etc/crowdsec/config/simulation.yaml
  #hub_dir: /etc/crowdsec/hub/
  #index_path: ./config/hub/.index.json
crowdsec_service:
  #acquisition_path: ./config/acquis.yaml
  parser_routines: 1
cscli:
  output: human
db_config:
  # removed for security
api:
  client:
    insecure_skip_verify: false # default true
    credentials_path: /etc/crowdsec/local_api_credentials.yaml
  server:
    #log_level: info
    listen_uri: 127.0.0.1:8080
    profiles_path: /etc/crowdsec/profiles.yaml
    online_client: # Central API
      credentials_path: /etc/crowdsec/online_api_credentials.yaml
prometheus:
- enabled: true
+ enabled: false
  level: full
```

I was able to make this change and restart the services with `docker compose restart`

### Monitoring moving forward

**I'll keep an eye on services again and come back here with results later this week.** That said, here's the output of `docker stats` a day after disabling Prometheus.

```bash
CONTAINER ID   NAME       CPU %     MEM USAGE / LIMIT     MEM %     NET I/O         BLOCK I/O         PIDS
0582af4781ca   pangolin   3.46%     196.1MiB / 1.922GiB   9.96%     412kB / 313kB   82.9MB / 283kB    22
c3f53591c5f4   traefik    1.53%     141.1MiB / 1.922GiB   7.17%     134MB / 119MB   97.1MB / 942kB    7
837f2ff2fe01   gerbil     0.00%     8.484MiB / 1.922GiB   0.43%     134MB / 119MB   7.81MB / 0B       3
b5442984a3f7   crowdsec   0.02%     135.9MiB / 1.922GiB   6.90%     695kB / 121kB   61.2MB / 7.09MB   14
```

**Reply by TuncTaylan** [reply]
It's strange, with just traefik and firewall bouncers my stats are:

```bash
CONTAINER ID   NAME       CPU %     MEM USAGE / LIMIT     MEM %     NET I/O          BLOCK I/O        PIDS
05a17307f7d0   traefik    0.08%     54.01MiB / 956.7MiB   5.65%     5.42MB / 3.8MB   241MB / 11.6MB   8
5189303534a9   gerbil     0.00%     5.418MiB / 956.7MiB   0.57%     5.42MB / 3.8MB   16.1MB / 627kB   5
77535852a96e   crowdsec   0.04%     103.9MiB / 956.7MiB   10.86%    926kB / 927kB    886MB / 40.5MB   17
d0efb069aed9   pangolin   16.90%    93.12MiB / 956.7MiB   9.73%     147kB / 611kB    281MB / 150MB    22
```

Prometheus is enabled, but I don't monitor it yet, so...

Do you have any other bouncers active?

Do you have any other services running or are you sure, that the RAM amount is not shared with other instances in your VPS provider?

**Reply by MykalMachon** [reply]
Turning off Prometheus slowed thing but CrowdSec is still growing slowly in RAM usage 😮‍💨 I really thought I had got it. 

- I don't have any custom bouncers setup 
- this is a dedicated VPS; I am sure as I have other workloads running on seperate VMs
- I can see through monitoring that the CrowdSec image is slowly growing in memory usage and almost nothing else is using any RAM on the system. 

Everything else is completely stock. Are there specific configs I should be posting? Here's my custom configurations; I do have a few extra pieces of config in place: 

## Home network postoverflow

file is located at `config/crowdsec/postoverflows/s01-whitelist`. This enables any requests coming from within my home network as it is a floating / dynamic IP that changes over time. 

```yaml
name: home/network 
description: "Whitelist events from home network's dynamic IP"
whitelist:
  reason: "Home Network Dynamic IP"
  expression:
      - evt.Overflow.Alert.Source.IP in LookupHost("vpn.machon.cloud")
```

## Immich parser 
file is located at `config/crowdsec/parsers/s02-enrich`. This stops false positive DoS requests coming from the immich mobile and web apps.

```yaml
name: machon/immich-whitelists
description: "Whitelist false positives from Immich-api"
filter: "evt.Meta.service == 'http' && evt.Meta.log_type in ['http_access-log', 'http_error-log']"
whitelist:
  reason: "Whitelist false positive from Immich-api"
  expression:
    - evt.Meta.http_verb == 'POST' && evt.Meta.http_status == '403' && evt.Parsed.request contains '/asset/upload'
    - evt.Meta.http_verb == 'GET' && evt.Meta.http_status == '429' && evt.Parsed.request contains '/api/asset/thumbnail/'
    - evt.Meta.http_verb == 'GET' && evt.Meta.http_status == '200' && evt.Parsed.request contains '/api/asset/thumbnail/'
    - evt.Meta.http_verb == 'GET' && evt.Meta.http_status == '304' && evt.Parsed.request contains '/api/asset/thumbnail/
```

### HTTP notification
I setup a webhook notification that pushes new bans out to my discord server via their webhooks / chatbots API. but it's very very simple 
```yaml 
type: http
name: discord
log_level: info
format: |
  {
    "content": "```\n{{range . -}}{{$alert := . -}}{{range .Decisions -}}- {{.Value}} will get **{{.Type}}** for the next '{{.Duration}}' for triggering '{{.Scenario}}'\n{{end -}}{{end -}}\n```"
  }

url: https://discord.com/api/webhooks/abcdefg
method: POST

headers:
  Content-Type: application/json
```
