### DISCUSSION TITLE
Add a 2nd domain

### DISCUSSION THREAD

**Discussion by KevinGaudry** [fosrl/pangolin#663] [Q&A] [answered]
Hello,

To clarify things first: I am no expert in traefik or else.

With this out of the way, I configured Pangolin with a wildcard cert for my domain and the dns challenge with the API from cloudflare (As in the documentation). All works well with different subdomains.
Now, I have a 2nd domain I would like to add to the same Pangolin instance and with the same setup, wildcard cert, dns challenge, same cloudflare account... Which files do I have to modify for this and how exactly ? I've been checking the documentation but it is not so clear to me, unfortunately.

Thanks for your support.

Kévin

**Comment by C8opmBM** [comment, marked as answer]
edit `/config/config.yml`

```
app:
  dashboard_url: https://pangolin.1dom.lol
  log_level: info
  save_logs: false
domains:
  domain1:
    base_domain: 1dom.lol
    cert_resolver: letsencrypt
    prefer_wildcard_cert: true
  domain2:
    base_domain: 2dom.lol
    cert_resolver: letsencrypt
    prefer_wildcard_cert: true
```

and in `/config/traefik/dynamic_config.yml`

```
    next-router:
      entryPoints:
        - websecure
      rule: Host(`pangolin.1dom.lol`) && !PathPrefix(`/api/v1`)
      service: next-service
      tls:
        certResolver: letsencrypt
        domains:
          - main: 1dom.lol
            sans:
              - '*.1dom.lol'
          - main: 2dom.lol
            sans:
              - '*. 2dom.lol'
          - main: 3dom.lol
            sans:
              - '*.3dom.lol'
```
