### DISCUSSION TITLE
How do i fix or debug a "timeout of 10000ms exceeded" for the dashboard?

### DISCUSSION THREAD

**Discussion by SpiderUnderUrBed** [fosrl/pangolin#780] [Q&A]
As the title says, when I try to login with the correct credentials, i get that error on the dashboard, and no abnormal logs
https://pastebin.com/ysMgTsX9
I changed some of the ports, but I tried to keep it as close as I could to defaults, here is the config:
```
listen: ":8080"

users:
  - name: spiderunderurbed
    email: SpiderUnderUrBed@proton.me
    password: (censored)
    groups: [admins]

routes:
  - path: /
    upstream: http://localhost:8000
    methods: [GET, POST]
    groups: [admins]

jwt:
  secret: (censored)
```
