### DISCUSSION TITLE
[Feature Request] CloudFlare proxy resource support

### DISCUSSION THREAD

**Discussion by LordG66** [fosrl/pangolin#812] [Feature Requests]
Hi guys,
First i would like to say that I am very impressed by pangolin, keep it up guys!

So, for my specific use-case I came across an issue.
I am using CloudFlare to protect all of my services and I wanted to integrate CF's Proxy features for all traffic going to the VPS hosting pangolin but I ran into an issue that the dynamic traefik templates that are generated by pangolin do no support anything else other then using the default letsencrypt certresolver.

Now, this issue only affects resources generated by users as in the pangolin configuration I was able to easily change the certificates as the feature is already built into the code.

My proposal is to integrate a mechanism to allow resources to use custom certificates thus allowing the usage of CF Proxy.

With the following changes and additions I am able to fully use cloudflare's proxy system to protect all access to any resource created and pangolin itself.

In pangolin's config.yaml:
```
app:
    dashboard_url: "https://pangolin.example.com"
    log_level: "debug"
    save_logs: false

domains:
    domain1:
        base_domain: "pangolin.example.com"
       #cert_resolver: "letsencrypt"
    domain2:
        base_domain: "example.com"

server:
    external_port: 3000
    internal_port: 3001
    next_port: 3002
    internal_hostname: "pangolin"
    session_cookie_name: "p_session_token"
    resource_access_token_param: "p_token"
    resource_access_token_headers:
        id: "P-Access-Token-Id"
        token: "P-Access-Token"
    resource_session_request_param: "p_session_request"
    secret: REDACTED
    cors:
        origins: ["https://pangolin.example.com"]
        methods: ["GET", "POST", "PUT", "DELETE", "PATCH"]
        headers: ["X-CSRF-Token", "Content-Type"]
        credentials: false

traefik:
    http_entrypoint: "web"
    https_entrypoint: "websecure"
```

For traefik the changes are -
traefik_config.yml:

```
entryPoints:
  web:
    address: :80
  websecure:
    address: :443
    http:
      middlewares:
        - crowdsec@file
    transport:
      respondingTimeouts:
        readTimeout: 30m
  tcp-25565:
    address: ":25565/tcp"
tls:
  certificates:
    - certFile: /etc/traefik/tls/cloudflare.crt
      keyFile: /etc/traefik/tls/cloudflare.key

  stores:
    default:
      defaultCertificate:
        certFile: /etc/traefik/tls/cloudflare.crt
        keyFile: /etc/traefik/tls/cloudflare.key
```

dynamic_config.yml:

```
tls:
  certificates:
    - certFile: /etc/traefik/tls/cloudflare.crt
      keyFile: /etc/traefik/tls/cloudflare.key
http:
  middleware:
     < default configuration >
  routers:
    api-router:
      entryPoints:
        - websecure
      middlewares:
        - security-headers
      rule: Host(`pangolin.example.com`) && PathPrefix(`/api/v1`)
      service: api-service
      tls: {}
    main-app-router-redirect:
      entryPoints:
        - web
      middlewares:
        - redirect-to-https
      rule: Host(`pangolin.example.com`)
      service: next-service
    next-router:
      entryPoints:
        - websecure
      middlewares:
        - security-headers
      rule: Host(`pangolin.example.com`) && !PathPrefix(`/api/v1`)
      service: next-service
      tls: {}
    ws-router:
      entryPoints:
        - websecure
      middlewares:
        - security-headers
      rule: Host(`pangolin.example.com`)
      service: api-service
      tls: {}
```
and the change in source code is for pangolin/server/routers/traefik/getTraefikConfig.ts
modifying the tls constant to check if an ENV var is present as TRUE to change the dynamic template

```
const tls = 
    process.env.CLOUDFLARE_PROXY === "TRUE"
    ? {}
    : {
        certResolver: configDomain.cert_resolver,
        ...(configDomain.prefer_wildcard_cert
            ? {
                    domains: [
                        {
                            main: wildCard
                        }
                    ]
                }
            : {})
};
```
