### DISCUSSION TITLE
Add additional root domains

### DISCUSSION THREAD

**Discussion by lthieman** [fosrl/pangolin#887] [Feature Requests]
I initially set up Pangolin and entered one of my domains during the installation script. But now I want to add a second root domain but there's no options for this anywhere in the GUI and no mention of it in the documentation.

**Comment by Lokowitz** [comment]
Hi @lthieman  
You have to edit `config/config.yml` and add the secound domain like:
```
domains:
  domain1:
    base_domain: "example1.com"
    cert_resolver: "letsencrypt"
  domain2:
    base_domain: "example2.com"
    cert_resolver: "letsencrypt"
```

Please restart your stack with:
```
docker compose down
docker compose up
```
