### DISCUSSION TITLE
Getting unifi working with pangolin

### DISCUSSION THREAD

**Discussion by MarcHagen** [fosrl/pangolin#973] [Q&A] [answered]
Hi there!

Im trying to get Unifi controller working with pangolin. 
However it seems that pangolin only allows one type of connection per subdomain and only HTTPs.
I can easily to the UI working, but the Unifi inform will not work.

Unifi has the norm that the `http://controller:8080/inform` needs to be HTTP. Devices will communicate over this `:8080` network.
The controller UI is running on `https://controller:8443/`.
 
Is there any way to make this work at the moment?

Current/old traefik labels
```yaml
    labels:
      traefik.enable: 'true'
      traefik.docker.network: cloud-public

      traefik.http.routers.unifi-controller-inform.rule: Host(`unifi.domain.tld`) && (Path(`/inform`) || PathPrefix(`/dl/firmware-cached`))
      traefik.http.routers.unifi-controller-inform.entrypoints: http
      traefik.http.routers.unifi-controller-inform.service: unifi-controller-inform-service
      traefik.http.services.unifi-controller-inform-service.loadbalancer.server.port: 8080

      traefik.http.routers.unifi-controller.rule: Host(`unifi.domain.tld`)
      traefik.http.routers.unifi-controller.entrypoints: https
      traefik.http.routers.unifi-controller.tls: 'true'
      traefik.http.routers.unifi-controller.tls.certresolver: le
      traefik.http.routers.unifi-controller.middlewares: chain-no-auth@file
      traefik.http.routers.unifi-controller.service: unifi-controller-service
      traefik.http.services.unifi-controller-service.loadbalancer.server.port: 8443
      traefik.http.services.unifi-controller-service.loadbalancer.server.scheme: https
```

**Comment by oschwartz10612** [comment]
I dont think this would be possible right now with pangolin. You might need to have pangolin route to a 2nd reverse proxy like traefik and use this trafik config. For example `unifi.domain.tld` in Pangolin would point to your 2nd Traefik instance on your network where it does this split based on the path. I guess that would requre the devices to use the same port though? Can you make the devices use the same port? 

If not, you could create raw pangolin TCP resources (https://docs.fossorial.io/Pangolin/tcp-udp) at 8443 and 8080 and point them to the 2nd load balancer on your network. 

I think we will add more powerful proxy control in the future!

**Reply by MarcHagen** [reply]
more powerful proxy control is an absolute must for being a serious replacement of Cloudflare.
I like the whole wireguard/newt/gerbil setup in Pangolin, why im using it at the moment! 

A second proxy that splits out could work.

Unifi does have an inform-url setting but is somewhat linked to the current hostname of Unify controller. So adding :8080 will probably work once after a sync it will be without the :8080 port part 😅

I'm going to fiddle with this over the weekend. Will see what will work.

I was also trying to just add it to the current dynamic_traefik yaml but I do not have a newt server port on the other side so that failed me for a bit. Maybe adding a random TCP resource in pangolin and using the server newt server ip/port 🤷🏻‍♂️ could be funky.

**Reply by MarcHagen** [reply, marked as answer]
Adding a dummy HTTP resource with somewhat random domain and add the endpoint to `unifi-controller` + `8080`. _Disable TLS for certs_

Then with `curl http://pangolin:3001/api/v1/traefik-config`, or traefik dashboard, find the service servers for the dummy resource and use that in the `dynamic_config.yml` 
```yaml
  routers:
    unifi-controller-inform:
      rule: "Host(`unifi.domain.tld`) && (Path(`/inform`) || PathPrefix(`/dl/firmware-cached`))"
      service: 26-service@http
      entryPoints:
        - web
```

And add a normal HTTPs resource for the normal domain `unifi.domain.tld` mapped to `unifi-controller` + `8443`

**Reply by MarcHagen** [reply]
UPDATE. 
No need for the dummy HTTP resource. However we cannot have HTTP+HTTPS in the same resource.
So you can add a extra Targets Configuration. This Targets Configuration can be used as a "service" in the custom router in the dynamic_config.yml

```
  routers:
    unifi-controller-inform:
      rule: "Host(`unifi.domain.tld`) && (Path(`/inform`) || PathPrefix(`/dl/firmware-cached`))"
      service: 20-inform-prefix-unifi-service@http
      entryPoints:
        - web
```
