### DISCUSSION TITLE
Docker Compose Setup

### DISCUSSION THREAD

**Discussion by Lokowitz** [fosrl/pangolin#99] [Feature Requests]
I am a fan of using docker compose with .env file for managing my containers.
Would be nice to get also Pangolin running with just filling the .env file and starting up the compose file.
I saw that there are some environment variables, USERS_SERVERADMIN_EMAIL and USERS_SERVERADMIN_PASSWORD are working fine. But when i define APP_DASHBOARDURL and APP_BASEDOMAIN i am getting an error in "config.ts".
The "config.yml" file gets created automatically but not "traefik_config.yml" and "dynamic_config.yml", just the "traefik" folder.

### docker-compose.yml
```
services:
  pangolin:
    image: fosrl/pangolin:${PANGOLIN_VERSION:-latest}
    container_name: pangolin
    restart: unless-stopped
    volumes:
      - ./config:/app/config
    environment:
      - APP_DASHBOARDURL=${DASHBOARDURL}
      - APP_BASEDOMAIN=${BASEDOMAIN}
      - USERS_SERVERADMIN_EMAIL=${SERVERADMIN_EMAIL}
      - USERS_SERVERADMIN_PASSWORD=${SERVERADMIN_PASSWORD}
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3001/api/v1/"]
      interval: "3s"
      timeout: "3s"
      retries: 5

  gerbil:
    image: fosrl/gerbil:${GERBIL_VERSION:-latest}
    container_name: gerbil
    restart: unless-stopped
    depends_on:
      pangolin:
        condition: service_healthy
    command:
      - --reachableAt=http://gerbil:3003
      - --generateAndSaveKeyTo=/var/config/key
      - --remoteConfig=http://pangolin:3001/api/v1/gerbil/get-config
      - --reportBandwidthTo=http://pangolin:3001/api/v1/gerbil/receive-bandwidth
    volumes:
      - ./config/:/var/config
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    ports:
      - 51820:51820/udp
      - 8080:8080 # Port for traefik because of the network_mode
      - 443:443 # Port for traefik because of the network_mode
      - 80:80 # Port for traefik because of the network_mode

  traefik:
    image: traefik:${TRAEFIK_VERSION:-v3.1}
    container_name: traefik
    restart: unless-stopped
    network_mode: service:gerbil # Ports appear on the gerbil service
    depends_on:
      pangolin:
        condition: service_healthy
    command:
      - --configFile=/etc/traefik/traefik_config.yml
    volumes:
      - ./config/traefik:/etc/traefik:ro # Volume to store the Traefik configuration
      - ./config/letsencrypt:/letsencrypt # Volume to store the Let's Encrypt certificates
```

### .env
```
#Container versions to use. You can pin this to a specific version like "1.0.0"
PANGOLIN_VERSION=latest
GERBIL_VERSION=latest
TRAEFIK_VERSION=v3.1

DASHBOARDURL=proxy.your.domain
BASEDOMAIN=your.domain
SERVERADMIN_EMAIL="email@your.domain"
SERVERADMIN_PASSWORD="super-secure-passwd"
```

![Unbenannt](https://github.com/user-attachments/assets/93e61eb5-7c16-4f0e-a02e-41aca6ab035c)

**Comment by miloschwartz** [comment]
I hope to add more environment variables in the future to allow people to use their preferred method. 

I am unable to reproduce the error you're getting by setting my domains with the variables. I am using:

```
services:
  pangolin:
    image: fosrl/pangolin:1.0.0-beta.8
    container_name: pangolin
    restart: unless-stopped
    environment:
      - APP_DASHBOARDURL=https://proxy.example.net
      - APP_BASEDOMAIN=example.net
    volumes:
      - ./config:/app/config
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3001/api/v1/"]
      interval: "3s"
      timeout: "3s"
      retries: 5
```

Does your domain have any special characters or numbers in it? I am wondering if maybe our regex is blocking it.

> The "config.yml" file gets created automatically but not "traefik_config.yml" and "dynamic_config.yml", just the "traefik" folder.

These files only get generated if you set the environment variable `GENERATE_TRAEFIK_CONFIG` to `true` in Pangolin.

**Comment by Lokowitz** [comment]
Thanks for the fast reply!
okay, for APP_DASHBOARDURL i missed "https://" in front - no errors now!

I did a complete new installation with:
### docker-compose.yml
```
services:
  pangolin:
    image: fosrl/pangolin:${VERSION_PANGOLIN:-latest}
    container_name: pangolin
    restart: unless-stopped
    volumes:
      - ./config:/app/config
    environment:
      - APP_DASHBOARDURL=https://${DASHBOARDURL}
      - APP_BASEDOMAIN=${BASEDOMAIN}
      - USERS_SERVERADMIN_PASSWORD=${SERVERADMIN_PASSWD}
      - USERS_SERVERADMIN_EMAIL=${SERVERADMIN_EMAIL}
      - GENERATE_TRAEFIK_CONFIG=true
    healthcheck:
      test:
        - CMD
        - curl
        - -f
        - http://localhost:3001/api/v1/
      interval: 3s
      timeout: 3s
      retries: 5
  gerbil:
    image: fosrl/gerbil:${VERSION_GERBIL:-latest}
    container_name: gerbil
    restart: unless-stopped
    depends_on:
      pangolin:
        condition: service_healthy
    command:
      - --reachableAt=http://gerbil:3003
      - --generateAndSaveKeyTo=/var/config/key
      - --remoteConfig=http://pangolin:3001/api/v1/gerbil/get-config
      - --reportBandwidthTo=http://pangolin:3001/api/v1/gerbil/receive-bandwidth
    volumes:
      - ./config/:/var/config
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    ports:
      - 44300:51820/udp
      - 443:443
      - 80:80
      - 8080:8080
  traefik:
    image: traefik:${VERSION_TRAEFIK:-v3.1}
    container_name: traefik
    restart: unless-stopped
    network_mode: service:gerbil
    depends_on:
      pangolin:
        condition: service_healthy
    command:
      - --configFile=/etc/traefik/traefik_config.yml
    environment:
      - IONOS_API_KEY=${API_IONOS}
    volumes:
      - ./config/traefik:/etc/traefik:ro
      - ./config/letsencrypt:/letsencrypt
```
### .env
```
VERSION_PANGOLIN = latest
VERSION_GERBIL = latest
VERSION_TRAEFIK = v3.1

DASHBOARDURL=proxy.my.domain
BASEDOMAIN=my.domain
SERVERADMIN_EMAIL = "email@my.domain"
SERVERADMIN_PASSWD = "super-secure-password"

API_IONOS = api-key
```

Now all files were created and the two traefik files are looking good (domain was replaced with my environment variable)
But the config.yml is still showing the example values.
I dont know if this is a problem because Pangolin is working fine and my admin login credentials are the one i set in the .env file.

### config.yml
```
app:
    dashboard_url: http://localhost:3002
    base_domain: localhost
    log_level: info
    save_logs: false

server:
    external_port: 3000
    internal_port: 3001
    next_port: 3002
    internal_hostname: pangolin
    secure_cookies: true
    session_cookie_name: p_session
    resource_session_cookie_name: p_resource_session
    resource_access_token_param: p_token

traefik:
    cert_resolver: letsencrypt
    http_entrypoint: web
    https_entrypoint: websecure

gerbil:
    start_port: 51820
    base_endpoint: localhost
    block_size: 24
    site_block_size: 30
    subnet_group: 100.89.137.0/20
    use_subdomain: true

rate_limits:
    global:
        window_minutes: 1
        max_requests: 100

users:
    server_admin:
        email: admin@example.com
        password: Password123!

flags:
    require_email_verification: false
    disable_signup_without_invite: true
    disable_user_create_org: true
```
