### ISSUE TITLE
http2 Support when choosing a Methode for a target

### ISSUE THREAD

**Issue by Doderich** [fosrl/pangolin#115]
Hey, I was wondering if there will be support for HTTP/2 as an option for a resource target.
![Image](https://github.com/user-attachments/assets/d65d51cc-ef04-46f7-bdc9-eb684ec7b1ee)

I'm using a self-hosted Zitadel instance as my Identity Provider, and Zitadel requires an h2c connection, at least from the proxy to the instance. This can be easily configured in Traefik by using h2c, as shown below:

```
auth:
      loadBalancer:
        servers:
          - url: "h2c://ip-adress:port"
        passHostHeader: true
```
I’m not sure how difficult it would be to implement this, but could you please take a look?

Thanks!
