### ISSUE TITLE
Multiple domains

### ISSUE THREAD

**Issue by miloschwartz** [fosrl/pangolin#140]
### Discussed in https://github.com/orgs/fosrl/discussions/68

<div type='discussions-op-text'>

<sup>Originally posted by **maieredv-manuel** January 16, 2025</sup>
Hey!

ive installed pangolin right now - looks nice :-) Great work!
Only downside i have until now is, that i cant add multiple Base Domains.
Im using different base domains for different services 
> own services are on servicexyz.mydomain.com
> customer services are on servicexyz.mydomain.cloud

Is there any way to do this?
 </div>

**Comment by dmull** [comment]
I see that this is marked done but not seeing any documentation on how to add the additional domains. Just wondering if I am overlooking things.

**Comment by jibsaram** [comment]
> I see that this is marked done but not seeing any documentation on how to add the additional domains. Just wondering if I am overlooking things.

I'm not sure if this is mentioned in more detail elsewhere, but the [documentation here](https://docs.fossorial.io/Pangolin/Configuration/config#domains) describes the `domains` configuration section. If you manually edit your `config.yml` file you'll find that there's already one domain configured (the one you set up with your Pangolin installation). There you can add additional domains, each with a unique key. E.g.:

```yaml
# (...snip...)
domains:
  domain1:
    base_domain: yourdomain.com
    cert_resolver: letsencrypt
    prefer_wildcard_cert: false
  domain2:
    base_domain: myseconddomain.com
    cert_resolver: letsencrypt
    prefer_wildcard_cert: false
```

I hope this helps!
