### ISSUE TITLE
project name must not be empty

### ISSUE THREAD

**Issue by nukularexperte** [fosrl/pangolin#190]
After configuration with the installer and pulling the container up the installation failed with "project name must not be empty" and prompt "installation complete!"
In the docker-compose.yml I simply added a line on top with name:pangolin
to fix it

**Comment by miloschwartz** [comment]
Interesting. Can you share your full docker compose with this snippet present? Never seen this before

**Comment by nukularexperte** [comment]
> Interesting. Can you share your full docker compose with this snippet present? Never seen this before

I just added the first line


```
name: pangolin
services:
  pangolin:
    image: fosrl/pangolin:1.0.0-beta.12
    container_name: pangolin
    restart: unless-stopped
    volumes:
      - ./config:/app/config
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3001/api/v1/"]
      interval: "3s"
      timeout: "3s"
      retries: 5


  gerbil:
    image: fosrl/gerbil:1.0.0-beta.3
    container_name: gerbil
    restart: unless-stopped
    depends_on:
      pangolin:
        condition: service_healthy
    command:
      - --reachableAt=http://gerbil:3003
      - --generateAndSaveKeyTo=/var/config/key
      - --remoteConfig=http://pangolin:3001/api/v1/gerbil/get-config
      - --reportBandwidthTo=http://pangolin:3001/api/v1/gerbil/receive-bandwidth
    volumes:
      - ./config/:/var/config
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    ports:
      - 51820:51820/udp
      - 443:443 # Port for traefik because of the network_mode
      - 80:80 # Port for traefik because of the network_mode


  traefik:
    image: traefik:v3.3.3
    container_name: traefik
    restart: unless-stopped

    network_mode: service:gerbil # Ports appear on the gerbil service


    depends_on:
      pangolin:
        condition: service_healthy
    command:
      - --configFile=/etc/traefik/traefik_config.yml
    volumes:
      - ./config/traefik:/etc/traefik:ro # Volume to store the Traefik configuration
      - ./config/letsencrypt:/letsencrypt # Volume to store the Let's Encrypt certificates

networks:
  default:
    driver: bridge
    name: pangolin
```
