### ISSUE TITLE
Secure SMTP does not work

### ISSUE THREAD

**Issue by Glow91** [fosrl/pangolin#203]
I tried to configure the email part and as my provider only shows the secure stuff on the page my config looks like this:

```
email:
    smtp_host: "smtp.strato.de"
    smtp_port: 465
    smtp_user: "printer@mydomain.de"
    smtp_pass: "xxxxxxxxx"
    smtp_secure: true
    no_reply: "printer@mydomain.de"
```

It looks like there is an Problem with the secure connection because this config results in an error loke this:

`2025-02-13T23:18:19.875Z [error]: Connection timeout
Stack: Error: Connection timeout
    at SMTPConnection._formatError (/app/node_modules/nodemailer/lib/smtp-connection/index.js:807:19)
    at SMTPConnection._onError (/app/node_modules/nodemailer/lib/smtp-connection/index.js:793:20)
    at Timeout.<anonymous> (/app/node_modules/nodemailer/lib/smtp-connection/index.js:237:22)
    at listOnTimeout (node:internal/timers:581:17)
    at process.processTimers (node:internal/timers:519:7) {"code":"ETIMEDOUT","command":"CONN"}`

After removing the smtp_secure property and set the port to 587 everything works fine.
For my usecase this ist just fine and I will use the unsecure connection, but maybe someone will have a look into it :)
