### ISSUE TITLE
Pangolin Doesn't Work with Subdomains as Base Domain

### ISSUE THREAD

**Issue by KamilKleina** [fosrl/pangolin#265]
Pangolin does not function when a subdomain is set as the base domain. I do not want to use domain.com as the base because it is already in use across multiple different servers. Instead, I need to set host-01.remote-location-01.domain.com as the base domain and have services like pangolin.host-01.remote-location-01.domain.com work normally.
Expected Behavior

    Pangolin should support subdomains as base domains.
    Certificates should issue and validate correctly.
    Routing should function as expected for services under the subdomain base.

Actual Behavior

    Pangolin fails entirely when using a subdomain as the base.

Steps to Reproduce

    Set the base domain to host-01.remote-location-01.domain.com.

**Comment by miloschwartz** [comment]
Hey, this should work; we use a subdomain as as a base domain internally, and I think some of our users in Discord do as well. However, it's possible it's still buggy. Can you provide some more info as to what happens when you attempt this and why it's failing? Are there are errors or anything in the logs that could provide us a hint?

**Comment by KamilKleina** [comment]
@miloschwartz 
so my config looks like it after running installer.sh (removed section about user and smtp)
 
```
app:
    dashboard_url: "https://pangolin.machine-01.cloud-01.domain.com"
    log_level: "info"
    save_logs: false

domains:
    domain1:
        base_domain: "machine-01.cloud-01.domain.com"
        cert_resolver: "letsencrypt"

server:
    external_port: 3000
    internal_port: 3001
    next_port: 3002
    internal_hostname: "pangolin"
    session_cookie_name: "p_session_token"
    resource_access_token_param: "p_token"
    resource_session_request_param: "p_session_request"
    cors:
        origins: ["https://pangolin.machine-01.cloud-01.domain.com"]
        methods: ["GET", "POST", "PUT", "DELETE", "PATCH"]
        headers: ["X-CSRF-Token", "Content-Type"]
        credentials: false

traefik:
    cert_resolver: "letsencrypt"
    http_entrypoint: "web"
    https_entrypoint: "websecure"
    prefer_wildcard_cert: false

gerbil:
    start_port: 51820
    base_endpoint: "pangolin.machine-01.cloud-01.domain.com"
    use_subdomain: false
    block_size: 24
    site_block_size: 30
    subnet_group: 100.89.137.0/20

rate_limits:
    global:
        window_minutes: 1
        max_requests: 100

flags:
    require_email_verification: true
    disable_signup_without_invite: true
    disable_user_create_org: false
    allow_raw_resources: true
    allow_base_domain_resources: true
```

and error is like that after running `docker logs pangolin`

```
Error: Invalid configuration file: Validation error: Invalid at "domains.domain1.base_domain"
```
