### ISSUE TITLE
Error: Invalid configuration file: Validation error: Required at "gerbil.site_block_size"

### ISSUE THREAD

**Issue by M3t4Data** [fosrl/pangolin#34]
Hello,
I encountered an issue when trying to start the Pangolin container after following the [Quick Install guide](https://docs.fossorial.io/Getting%20Started/quick-install). I followed the instructions exactly as described, without making any special configuration changes. However, the pangolin container fails to start with the following error:

```
Starting migrations from version 1.0.0-beta.3
All migrations completed successfully
/app/server/lib/config.ts:158
            throw new Error(`Invalid configuration file: ${errors}`);
                  ^


Error: Invalid configuration file: Validation error: Required at "gerbil.site_block_size"
    at Config.loadConfig (/app/server/lib/config.ts:158:19)
    at new Config (/app/server/lib/config.ts:91:14)
    at <anonymous> (/app/server/lib/config.ts:202:23)

Node.js v20.18.1
```

To troubleshoot, I modified the docker-compose.yml file to use the 1.0.0-beta.2 version of the Pangolin image instead of 1.0.0-beta.3. With this version, the container starts correctly without any issues.

Thank you for this tool and your work!

**Comment by oschwartz10612** [comment]
Try to put `site_block_size: 29` manually into the gerbil section of the config and try again. The beta.3 migration is supposed to do that for you but it seems like maybe it is not? We are looking into it...

https://docs.fossorial.io/Pangolin/Configuration/config#gerbil

**Comment by oschwartz10612** [comment]
Actually if you have the `subnet_group: 100.89.137.0/20` then use `site_block_size: 30`

Did you install manually or with the installer?

**Comment by M3t4Data** [comment]
I installed Pangolin using the provided binary "installer". The configuration that was generated for the gerbil section is as follows:

```yaml
gerbil:  
    start_port: 51820  
    base_endpoint: (redacted)  
    use_subdomain: false  
    block_size: 16  
    subnet_group: 10.0.0.0/8
```

I tried reinstalling Pangolin on another VM, and this time the configuration for the gerbil section was different. It looked like this during my test:

```yaml
gerbil:  
    start_port: 51820  
    base_endpoint: (redacted)  
    use_subdomain: false  
    block_size: 24  
    site_block_size: 30  
    subnet_group: 100.89.137.0/20  
```

It seems like the site_block_size was correctly generated this time and the container run perfectly. Maybe I missed something during the first installation without realizing it ...
