### ISSUE TITLE
URL redirect

### ISSUE THREAD

**Issue by miloschwartz** [fosrl/pangolin#349]
### Discussed in https://github.com/orgs/fosrl/discussions/245

<div type='discussions-op-text'>

<sup>Originally posted by **strich3** February 27, 2025</sup>
Add a redirect option to the rules, for example:

If you want people to get redirected from website.xyz/somethingold to website.xyz/somethingnew

Very simple but could be useful </div>

**Comment by snagcustoms** [comment]
Another version of this would be something in the gui to mimic this feature in nginx: `location = /{return 301 $scheme://$http_host/foldername;}`

**Comment by Fred-06** [comment]
Hi,

Also interested in this feature.

Useful for example to implement oCIS and make the application work on smartphones for example because there is a Redirect URI.

Thanks a lot for the work!

**Comment by kmanwar89** [comment]
+1 here please and thank you!

I'd like to redirect "api.mydomain.com" directly to "api.mydomain.com/v1/docs" when I'm accessing it via my browser, without breaking the api.mydomain.com/v1 internal health checks.

**Comment by L0sWach0s** [comment]
I‘m also interested in this feature!

By the way:

Great job!

**Comment by aaymecho** [comment]
This would be good, but in the meantime you configure traefik's config dynamic config to get a similar setup.

Example: pangolin.websitename.org/old -> new.websitename.org
```
redirect-to:
      redirectRegex:
        regex: "^https?://pangolin\\.websitename\\.org/old.*"
        replacement: "https://new.websitename.org"
        permanent: true
```

also great job guys!
