### ISSUE TITLE
Bandwith Issue

### ISSUE THREAD

**Issue by Karsto-sys** [fosrl/pangolin#410]
Hello,

I'm encountering bandwidth issues with Pangolin and need help debugging.

I'm running an OpenSpeedTest container on my Unraid setup and expect to achieve a minimum of 150 Mbit/s. However, currently, I'm only getting a maximum of around 40 Mbit/s, occasionally dropping below 2 Mbit/s.

### Troubleshooting Attempt
I've attempted to manually check the endpoint with `curl` and received a 404 error:

```shell
root@39809a2dddeb:/# curl http://pangolin:3001/api/v1/gerbil/receive-bandwidth
{"data":null,"success":false,"error":true,"message":"The requests url is not found - /api/v1/gerbil/receive-bandwidth","status":404,"stack":null}
```

### Docker Compose Setup

Here is my Docker Compose configuration:

```yaml
services:
  pangolin:
    image: fosrl/pangolin:latest
    container_name: pangolin
    restart: unless-stopped
    volumes:
      - ./config:/app/config
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3001/api/v1/"]
      interval: "3s"
      timeout: "3s"
      retries: 5

  gerbil:
    image: fosrl/gerbil:latest
    container_name: gerbil
    restart: unless-stopped
    depends_on:
      pangolin:
        condition: service_healthy
    command:
      - --reachableAt=http://gerbil:3003
      - --generateAndSaveKeyTo=/var/config/key
      - --remoteConfig=http://pangolin:3001/api/v1/gerbil/get-config
      - --reportBandwidthTo=http://pangolin:3001/api/v1/gerbil/receive-bandwidth
    volumes:
      - ./config/:/var/config
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    ports:
      - 51820:51820/udp
      - 443:443 # Port for traefik because of the network_mode
      - 80:80 # Port for traefik because of the network_mode

  traefik:
    image: traefik:v3.1
    container_name: traefik
    restart: unless-stopped
    network_mode: service:gerbil
    depends_on:
      pangolin:
        condition: service_healthy
    command:
      - --configFile=/etc/traefik/traefik_config.yml
    environment:
      CF_DNS_API_TOKEN: "<***>"
    volumes:
      - ./config/traefik:/etc/traefik:ro
      - ./config/letsencrypt:/letsencrypt
```
on my vps i get following speeds:

`Download: 2543.84 Mbit/s
Upload: 594.26 Mbit/s`

I appreciate any guidance on resolving this bandwidth issue. Thank you!
