### ISSUE TITLE
Invalid target IP with a wireguard config

### ISSUE THREAD

**Issue by SeiyaGame** [fosrl/pangolin#433]
The goal I have here is to set up a WireGuard configuration on my OPNsense in order to securely provide access to all my VLANs.

So I added a site and used the basic WireGuard tunnel configuration 
At that point, it generated the following WireGuard configuration:

```ini
[Interface]
Address = 100.89.128.8/30
ListenPort = 51820
PrivateKey = iEJSNHnMS7CEGg0XIKR/6Uzk4jKCxX+6hUgvDWE7Q2U=

[Peer]
PublicKey = qUV+OIICNzGUgqHBSreZzlG9aOgTPnwtWZFej7/GllY=
AllowedIPs = 100.89.128.1/32
Endpoint = mydomain.here:51820
PersistentKeepalive = 5
```

Already at this point, I can see that it's not possible to configure the AllowedIPs.
On my OPNsense, I added the configuration, and for the peer, I included all the subnets that I want Gerbil to have access to under AllowedIPs.
The WireGuard tunnel is successfully established on both sides at this point.

Next, I added a resource and then a connectivity.
In the Target Configuration, I entered the IP of the service I want to make accessible, which is 192.168.1.5/24 but could be other local IP

I get the following error message:

![Image](https://github.com/user-attachments/assets/f5898de6-67e6-4374-9ff2-47e4fcd01119)

From what I understand, I can only enter an IP from this range: 100.89.128.0
I don’t understand why :/

---

`config/config.yml`

```yml
...
gerbil:
    start_port: 51820
    base_endpoint: "mydomain.here"
    use_subdomain: false
    block_size: 24
    site_block_size: 30
    subnet_group: 100.89.128.1/24
...
```
