### ISSUE TITLE
Wildcard Certs in Multiple Domains

### ISSUE THREAD

**Issue by Tanhueco** [fosrl/pangolin#464]
I tried this out but the website does not come up.  Is it possible to have wildcard certificates issued to mutiple domains?

dynamic_config.yml:

    next-router:
       entryPoints:
         - websecure
       middlewares:
         - security-headers
       rule: Host(`proxy.domain1.com`) && !PathPrefix(`/api/v1`)
       service: next-service
       tls:
         certResolver: letsencrypt
         domains[0]:
           - main: "domain1.com"
             sans:
               - "*.domain1.com"
         domains[1]:
           - main: "domain2.com"
             sans:
               - "*.domain2.com"

A single domain works ok:

    next-router:
       entryPoints:
         - websecure
       middlewares:
         - security-headers
       rule: Host(`proxy.domain1.com`) && !PathPrefix(`/api/v1`)
       service: next-service
       tls:
         certResolver: letsencrypt
         domains:
           - main: "domain1.com"
             sans:
               - "*.domain1.com"

**Comment by Lokowitz** [comment]
Hi  Tanhueco,

when i remember correct it should work like this:
```
     domains:
       - main: "domain1.com"
         sans:
           - "*.domain1.com"
       - main: "domain2.com"
         sans:
           - "*.domain2.com"
```

Are you using the same provider for all domains?

**Comment by Tanhueco** [comment]
@Lokowitz,  That works!

Yes, all domains are from the same provider.

**Comment by miloschwartz** [comment]
Thanks @Lokowitz!

**Comment by nlsrchtr** [comment]
Hi @Lokowitz,

could you help me out, when I have multiple wildcard domains with different providers? How would I adjust the certificatesResolvers in a way, that it would pick up the correct configuration per domain?

```yaml
certificatesResolvers:
  letsencrypt:
    acme:
      httpChallenge:
        entryPoint: web
      email: hello@example.com # REPLACE THIS WITH YOUR EMAIL
      storage: "/letsencrypt/acme.json"
      caServer: "https://acme-v02.api.letsencrypt.org/directory"
```

Thanks a lot for your help or any pointers!

Regards,
