### ISSUE TITLE
Option for non-HTTP resources not showing in the "Create Resource" dialog

### ISSUE THREAD

**Issue by Viduct** [fosrl/pangolin#492]
Hello,

I was able to set up the Pangolin stack and everything (including my services) seems to work just fine, but for some reason I am only able to create raw UDP/TCP resources:

![Image](https://github.com/user-attachments/assets/4d79e664-7ed2-4bdb-bb70-fe1f12bdbaec)

I already went step-by-step through your documentation (https://docs.fossorial.io/Pangolin/tcp-udp). Is there anything else I needed to enable raw UDP/TCP resources?

Versions:
Pangolin: 1.2.0
Gerbil: 1.0.0
Traefik: 3.3.5
Badger: 1.1.0
Newt: 1.1.3

**Comment by oschwartz10612** [comment]
Make sure you have `allow_raw_resources` set to `true` in your `config.yml`. 

```
flags:
  require_email_verification: false
  disable_signup_without_invite: false
  disable_user_create_org: false
  allow_raw_resources: true
```
