### ISSUE TITLE
Unable to send invitation email to user

### ISSUE THREAD

**Issue by zulredfrog** [fosrl/pangolin#498]
I have configured the email part in the configuration file with following configuration:

```
 email:
        smtp_host: "smtp.resend.com"
        smtp_port: 587
        smtp_user: "resend"
        smtp_pass: "XXXXXXXXXX"
        no-reply: "no-reply@mydomain.com"
```

When I tried to send invite email to user, I encountered this error:

```
2025-04-09T10:03:04.687Z [error]: Mail command failed: 501 Error: Bad sender address syntax
Stack: Error: Mail command failed: 501 Error: Bad sender address syntax
    at SMTPConnection._formatError (/app/node_modules/nodemailer/lib/smtp-connection/index.js:807:19)
    at SMTPConnection._actionMAIL (/app/node_modules/nodemailer/lib/smtp-connection/index.js:1616:34)
    at SMTPConnection.<anonymous> (/app/node_modules/nodemailer/lib/smtp-connection/index.js:1085:18)
    at SMTPConnection._processResponse (/app/node_modules/nodemailer/lib/smtp-connection/index.js:991:20)
    at SMTPConnection._onData (/app/node_modules/nodemailer/lib/smtp-connection/index.js:772:14)
    at SMTPConnection._onSocketData (/app/node_modules/nodemailer/lib/smtp-connection/index.js:195:44)
    at TLSSocket.emit (node:events:524:28)
    at addChunk (node:internal/streams/readable:561:12)
    at readableAddChunkPushByteMode (node:internal/streams/readable:512:3)
    at Readable.push (node:internal/streams/readable:392:5) {"code":"EENVELOPE","response":"501 Error: Bad sender address syntax","responseCode":501,"command":"MAIL FROM"}

```

I also tried to use SMTP port 465 with `smtp_secure: true` config but still encountered the same error. I've tested the SMTP host with cURL test through both ports (465 & 587, SSL & TLS), seems working and the email was sent and received.

I saw OP in issue #203 was able to make it work using port 587, so I'm not sure why it's not working and wonder if anyone had encountered this similar issue before.

**Comment by miloschwartz** [comment]
Hey there has been some discussion about using Resend in our Discord server. Looks like it's been solved there. Take a look at: https://discord.com/channels/1325658630518865980/1351266041564762122

**Comment by zulredfrog** [comment]
Hey! Thanks for the guidance. I've followed the recommended setup from Resend based on the Discord thread and able to make it work.

I got it working by using port 2465 and set `smtp_secure: true` : 

```
 email:
        smtp_host: "smtp.resend.com"
        smtp_port: 2465
        smtp_user: "resend"
        smtp_pass: "XXXXXXXXXX"
        smtp_secure: true
        no-reply: "no-reply@mydomain.com"
```

Thanks again!
