### ISSUE TITLE
Redirect loop on additional domains

### ISSUE THREAD

**Issue by bhagen55** [fosrl/pangolin#538]
Hello!
I have been using Pangolin and it has been flawless with a single domain.
I tried adding two additional domains and have not been able to get them working.

I have set up a simple resource that points to a static HTML site hosted by a NGINX docker container.
If I point the resource at my first domain in "General Settings", the page loads fine. If I point it at one of my secondary domains, it gets into a redirect loop.

(redacted my domain and IP addresses)
```
--2025-04-16 17:46:46--  https://test.mydomain.com/
Resolving test.mydomain.com (test.mydomain.com)... 1.2.3.4, 1.2.3.4, 1:2:3:4, ...
Connecting to test.mydomain.com (test.mydomain.com)|1.2.3.4|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://test.mydomain.com/ [following]
--2025-04-16 17:46:46--  https://test.mydomain.com/
Reusing existing connection to test.mydomain.com:443.
HTTP request sent, awaiting response... 302 Found
Location: https://test.mydomain.com/ [following]
--2025-04-16 17:46:46--  https://test.mydomain.com/
Reusing existing connection to test.mydomain.com:443.
HTTP request sent, awaiting response... 302 Found
Location: https://test.mydomain.com/ [following]
```

I do have Crowdsec enabled, but I don't see anything related in it's logs when I try to load the page.

I am running Pangolin v1.2.0 in a docker compose stack.
Here is the domains section of my config:
```
domains:
  domain1:
    base_domain: domain1.com
    cert_resolver: letsencrypt
  domain2:
    base_domain: mydomain.com
    cert_resolver: letsencrypt
  domain3:
    base_domain: mydomain2.com
    cert_resolver: letsencrypt
```

**Comment by oschwartz10612** [comment]
If you attempt to visit the 2nd domain with an incognito window or private window does it work?

**Comment by bhagen55** [comment]
It does not work in incognito or with a fresh cache.

**Comment by miloschwartz** [comment]
A few more question to try to pin point the problem:

Are Pangolin and Badger both fully up to date?

When you start Traefik do you see any errors related to requesting and confirming a certificate? Make sure DNS is set up for those extra domains and they can gain a valid cert all through the same cert resolver (`letsencrypt`).

During the redirect loop, do you see any errors or anything printed in the Pangolin server logs? If you enable `debug` log level for Pangolin, do you see it continuously requesting session cookies during the redirect loop?

**Comment by bhagen55** [comment]
I am using `image: fosrl/pangolin:1.2.0` and badger:
```
experimental:
  plugins:
    badger:
      moduleName: github.com/fosrl/badger
      version: v1.1.0
```

I believe those are up to date.

Good call on the SSL side of things, I turned off SSL on one of the problem domains and it loads fine via normal HTTP. I will poke around the Traefik logs to see if I can figure out what is wrong with cert requests.
