### ISSUE TITLE
internal server error

### ISSUE THREAD

**Issue by migandhi** [fosrl/pangolin#549]
Hi,

I have a website 
That was working fine with ngrok tunneling ngrok http 8080
It is locally hosted
But when I use it as pangolin resource

I get "internal server error"

And one other streaming application also
was working good with ngrok http 8050

But it results in error while using pangolin, 
like "error loading video"

Why I cannot get a high quality connection in comparison?

Regards.

**Comment by migandhi** [comment]
This problem is related to https, 
when I removed https from target resource, I resolved the issues ,
I should only create http target resource
Why?

Also I hope there would be no further issues.

I am also curious how to make a TCP target resource,
for example hosting game server, or communication server on a port
using TCP protocol instead of http

I also saw the h2c option , what is it?

So far I think this is a very useful project
I like it very much
Hope these are only minor issues.

Thanks,
Regards.

**Comment by LKStu** [comment]
Joining this as I had the same experience. Why does only http work? Seems insecure but I also enabled SSL (https) sooo?

**Comment by zandercodes** [comment]
I have a similar problem.

I also get an “Internal Server Error” although everything is set correctly.

I can reach the website from the container with traefik and garbil via the wireguard ip + port, but when I do the route set with traefik and pangolin, I don't get the website but the “Internal Server Error”.

EDIT:
I don't know what the problem was but I reinstalled the pangolin once and now it works

**Comment by miloschwartz** [comment]
This could be related to the internal_hostname set in the config. The other containers in the stack need to be able to address Pangolin internally by that hostname. We've seen this cause Internal Server Error for others.

Glad you were able to get it working!

**Comment by zandercodes** [comment]
> This could be related to the internal_hostname set in the config. The other containers in the stack need to be able to address Pangolin internally by that hostname. We've seen this cause Internal Server Error for others.
> 
> Glad you were able to get it working!

that could have been the problem “internal_hostname” was previously set to ‘localhost’ and then changed it to “pangolin” during the new installation

**Comment by reitenth** [comment]
im trying to setup pangolin with pelican-panel/wings. i got everything good but the last step. wings gives me a 
`Internal Server Error`. i already changed `internal_hostname` to pangolin with no luck.

**Comment by zandercodes** [comment]
> im trying to setup pangolin with pelican-panel/wings. i got everything good but the last step. wings gives me a `Internal Server Error`. i already changed `internal_hostname` to pangolin with no luck.

pelican-panel/wings is based on pterodactly/wings. The only difference is the design.
wings and pangolin must be in the same network in Docker and the `container_name` of pangolin must be the same as the `internal_hostname` of the configuration of pangolin.

docker-compose.yml:
```yaml
services:
  pangolin:
    image: fosrl/pangolin:1.4.0
    container_name: pangolin
    restart: unless-stopped
    volumes:
      - /opt/pangolin:/app/config
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3001/api/v1/"]
      interval: "3s"
      timeout: "3s"
      retries: 15

  gerbil:
    image: fosrl/gerbil:1.0.0
    container_name: gerbil
    restart: unless-stopped
    depends_on:
      pangolin:
        condition: service_healthy
    #entrypoint: ["/var/config/start.sh"]
    command:
      - --reachableAt=http://gerbil:3003
      - --generateAndSaveKeyTo=/var/config/key
      - --remoteConfig=http://pangolin:3001/api/v1/gerbil/get-config
      - --reportBandwidthTo=http://pangolin:3001/api/v1/gerbil/receive-bandwidth
    volumes:
      - /opt/pangolin:/var/config
    dns: 1.1.1.1
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    ports:
      - 51820:51820/udp
      - 443:443
      - 80:80
      # ALL GAME PORTS YOUR A USED
      - 2022:2022 # WINGS SFTP PORT

  traefik:
    image: traefik:v3.3.3
    container_name: traefik
    restart: unless-stopped
    network_mode: service:gerbil
    depends_on:
      pangolin:
        condition: service_healthy
    command:
      - --configFile=/etc/traefik/traefik_config.yml
    volumes:
      - /opt/pangolin/traefik:/etc/traefik:ro
      - /opt/pangolin/letsencrypt:/letsencrypt

  wings:
    ...
    network_mode: service:gerbil
    # REMOVE ALL PORTS

  panel:
    ...
    networks:
      - default
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.panel.rule=Host(`panel.yourdomain.com`)"
      - "traefik.http.routers.panel.tls=true"
      - "traefik.http.routers.panel.tls.certresolver=resolver"
      - "traefik.http.services.panel.loadbalancer.server.port=443"

networks:
  default:
    driver: bridge
    name: pangolin
```
pangolin config.yml
```yaml
...
server:
  ...
  internal_hostname: "pangolin"
  ...
...
```
for example but not testet
