### ISSUE TITLE
DNS challenge isn't working with cloudflare

### ISSUE THREAD

**Issue by cantchooseaname8** [fosrl/pangolin#553]
The DNS challenge isn't working with cloudflare. All of the configs are set up and it correctly adds the necessary txt records to my domain's dns. So it clearly has access to add the txt records, but traefik does not seem to even recognize them. The logs for traefik always result in an error saying the propagation time limit was exceeded. I have it set up and working perfectly in NPM without any issues. I was also able to generate certs through caddy with a dns challenge for cloudflare. I'm not sure if there is something broke with the implementation between traefik and cloudflare, but it seems to just ignore the txt records for the dns challenge and no certs are issued.

Here is what the records show (changed the name of my actual domain to domain.com so it's not listed here):

`ERR Unable to obtain ACME certificate for domains error="unable to generate a certificate for the domains [pangolin.domain.com]: error: one or more domains had a problem:\n[pangolin.domain.com] propagation: time limit exceeded: last error: authoritative nameservers: NS porter.ns.cloudflare.com.:53 returned REFUSED for domain.com.\n" ACME CA=https://acme-v02.api.letsencrypt.org/directory acmeCA=https://acme-v02.api.letsencrypt.org/directory domains=["pangolin.domain.com"] providerName=letsencrypt.acme routerName=api-router@file rule="Host(`pangolin.domain.com`) && PathPrefix(`/api/v1`)"`

**Comment by miloschwartz** [comment]
It's a good sign you can see it adding the DNS records to CloudFlare. I wonder if Traefik is prematurely reporting a failure if it's taking a little too long to propagate. Does this happen every time you restart? You could try to mess with the propagation settings here: https://doc.traefik.io/traefik/https/acme/#propagationdisablechecks

**Comment by cantchooseaname8** [comment]
Thanks for the quick response. Unfortunately no such luck messing with the propagation settings. I tried setting it to delay for another 60s, but it still doesn't seem to recognize the dns records and get the cert. I had the same issue when I recently tested Zoraxy. There's an open issue on their GitHub page for this as well and it was confirmed to no longer work with cloudflare. Maybe something changed with cloudflare and the traefik/cloudflare integration also broke and is no longer working correctly?

**Comment by ex-aequo-et-bono** [comment]
Had a similar situation when pulling a wildcard cert earlier. Are you intending to request a pangolin subdomain cert in addition to others (i.e., *.FQD.com **_and_** pangolin.fqd.com)? Was deploying and trying to only get a wildcard and the base domain cert, but because of the way traefik's dynamic config is configured it tried to pull the subdomain also (fqd.com, *.fqd.com, _**and**_ pangolin.fqd.com). It seems based on your error it is pulling a pangolin.fqd.com cert as well--if that's not intended that may be related to the issue?

**Comment by cantchooseaname8** [comment]
Interesting thought. Is there a way to prevent it from trying to pull pangolin.fqd.com? I can give that a try and see if it resolves. I'd rather pangolin.fqd.com just use the wildcard cert instead of having its own cert issued, but I don't see how to prevent it from doing that.

**Comment by ex-aequo-et-bono** [comment]
I'll let others that are more familiar with Traefik chime in, as I'm truthfully not all that familiar. If helpful, my config is below. (Note I have my middlewares on my static config, but don't think deviation from the default pangolin config affects anything.)

Not sure how I resolved it earlier, but upon reflection I think you could probably spin everything down, sudo rm /letsencrypt/acme.json, and then edit the dynamic config to remove "pangolin" in front of the router Host rules (so it would _**just**_ be the base domain + however you've configured to pull the wildcard certs and there's no chance it could accidentally pull pangolin.fqd.com since it doesn't exist anywhere), and then spin it up again. Once it pulls the base domain + wildcard certs you could just edit the dynamic config and throw the 'pangolin' back in front of the router Hosts and it should use the wildcard cert. 


Curious if others have encountered this and if so what the best way to resolve the issue would be.



Dynamic config:
```  
routers:
    api-router:
      entryPoints:
        - websecure
      rule: Host(`pangolin.domain2.com`) && PathPrefix(`/api/v1`)
      service: api-service
      tls:
        certResolver: letsencrypt

    main-app-router-redirect:
      entryPoints:
        - web
      rule: Host(`pangolin.domain2.com`)
      service: next-service

    next-router:
      entryPoints:
        - websecure
      rule: Host(`pangolin.domain2.com`) && !PathPrefix(`/api/v1`)
      service: next-service
      tls:
        certResolver: letsencrypt
        domains:
          - main: domain1.com
            sans:
              - '*.domain1.com'
          - main: domain2.com
            sans:
              - '*.domain2.com'
          - main: domain3.com
            sans:
              - '*.domain3.com'

    ws-router:
      entryPoints:
        - websecure
      rule: Host(`pangolin.domain2.com`)
      service: api-service
      tls:
        certResolver: letsencrypt

  services:
    api-service:
      loadBalancer:
        servers:
          - url: http://pangolin:3000

    next-service:
      loadBalancer:
        servers:
          - url: http://pangolin:3002
```

My static config:
```
certificatesResolvers:
  letsencrypt:
    acme:
      caServer: https://acme-v02.api.letsencrypt.org/directory
      email: admin@domain2.com
      storage: /letsencrypt/acme.json
      dnsChallenge:
        provider: cloudflare
        resolvers:
          - 1.1.1.1:53
          - 1.0.0.1:53

entryPoints:
  web:
    address: ':80'
    http:
      middlewares:
        - redirect-to-https@file
  websecure:
    address: ':443'
    transport:
      respondingTimeouts:
        readTimeout: 30m
    http:
      tls:
        certResolver: letsencrypt
      middlewares:
        - crowdsec@file
        - my-GeoBlock@file
        - security-headers@file
```

**Comment by cantchooseaname8** [comment]
Thanks for sharing that. I might mess around with it and try to get it to work, but I’ll probably just go back to NPM in the meantime and keep an eye on this. Pangolin seems so promising and I’ve been following it for a little while now. Hopefully this issue will get squared away at some point.

**Comment by Chanceium** [comment]
similar issue, my certs are no longer regenerating for all my pangolin resources.

**Comment by cantchooseaname8** [comment]
So I tested this a little more and noticed something else. When I start pangolin, traefik will create a few dns txt records in cloudflare. It created three records. For the sake of keeping it simply, let's say it was the following three:

1) abc
2) def
3) ghi

After the first timeout, the error said it was looking for the def record which was clearly there. The "def" record was also automatically removed from cloudflare since it's short lived, but the other two remained. Then traefik tried again and the error said it was looking for the abc record which was also clearly there. Then both of the last two records were automatically removed from cloudflare (abc and ghi)

For some reason it just isn't reading the dns records correctly. The value it's looking for is there, but it just can't see it. At the end of the error message, it also shows "v=spf1 -all". It's almost as if it's pulling the txt record for my spf instead of the correct txt record for the dns challenge.

Anyway, maybe this will give someone a little more insight into a possible fix.

**Comment by w1tw0lf** [comment]
Just checked if mine still works and created 2 new cert without issue, does take long.

My traefik_config.yml:

```
......
certificatesResolvers:
 letsencrypt:
   acme:
     email: "mail@mail.com"
     storage: "/letsencrypt/acme.json"
     dnsChallenge:
       delayBeforeCheck: 0
       provider: cloudflare
       resolvers:
         - 1.1.1.1:53
         - 8.8.8.8:53
         - 9.9.9.9:53
.....
```
in docker-compose.yml, under traefik

```
.......
   environment:
     CF_DNS_API_TOKEN: dfsdfggd........
     CLOUDFLARE_DNS_API_TOKEN: dfsdfggd........
     CLOUDFLARE_POLLING_INTERVAL: 10
     CLOUDFLARE_PROPAGATION_TIMEOUT: 300
     CLOUDFLARE_TTL: 300
.......
```
