### ISSUE TITLE
[Feature Request] Ability to set passHostHeader to false on Auto created service for resource target

### ISSUE THREAD

**Issue by oidebrett** [fosrl/pangolin#565]
Currently, when you create a new resource and map this to a target, a service gets configured in Traefik. By default, this service sets the passHostHeader to true 

There are some cases where its required to set passHostHeader to false such as when you are trying to proxy to an existing publicly accessible website which its own ssl.

for example  

```
http:
  routers:
    add-http-router:
      rule: "Host(add.mydomain.com)"
      entryPoints:
        - websecure
      service: add-http-service
      tls: {}

  services:
    add-http-service:
      loadBalancer:
        servers:
          - url: "https://remote.externaldomain.com:443"
        passHostHeader: false  # <--- Important but doesnt get created by Pangolin nor any option for it
```
