### ISSUE TITLE
Expand Wireguard Subnet

### ISSUE THREAD

**Issue by duffman36** [fosrl/pangolin#573]
Great project. Really nice looking and works well.

One thing. Is there a way to expand or specify the Wireguard subnet? I have a few ideas but i need the subnets to be larger.

**Comment by oschwartz10612** [comment]
In your config file there is a gerbil section which defines how each site's address is chosen.
```
gerbil:
    start_port: 51820
    block_size: 24
    site_block_size: 30
    subnet_group: 100.89.137.0/20 
````
