### ISSUE TITLE
[Bug] Default Pangolin setup with Badger not properly forwarding real IP's via Cloudflare/IP based rules not working with Cloudflare

### ISSUE THREAD

**Issue by slimshizn** [fosrl/pangolin#619]
Have added the following to `traefik_config.yml`

```
entryPoints:
  web:
    address: :80
    forwardedHeaders:
      trustedIPs: &trustedIps
        - 172.18.0.0/16
        # CF
        - 173.245.48.0/20
        - 103.21.244.0/22
        - 103.22.200.0/22
        - 103.31.4.0/22
        - 141.101.64.0/18
        - 108.162.192.0/18
        - 190.93.240.0/20
        - 188.114.96.0/20
        - 197.234.240.0/22
        - 198.41.128.0/17
        - 162.158.0.0/15
        - 104.16.0.0/12
        - 172.64.0.0/13
        - 131.0.72.0/22
        - 2400:cb00::/32
        - 2606:4700::/32
        - 2803:f800::/32
        - 2405:b500::/32
        - 2405:8100::/32
        - 2a06:98c0::/29
        - 2c0f:f248::/32
        # CF
  websecure:
    address: :443
    forwardedHeaders:
      # Reuse list of Cloudflare Trusted IP's above for HTTPS requests
      trustedIPs: *trustedIps
```

Can see my IP hit via the traefik acces.log but IP based rules are still not working. Only will work via disabling orange cloud in cloudflare.

Example log
```
{"ClientAddr":"172.70.43.54:52720","ClientHost":"<MYIP>","DownstreamContentSize":0,"DownstreamStatus":304,"Duration":675516329,"RequestMethod":"GET","RequestPath":"/cover/168655/sm?c=1741857025","RequestProtocol":"HTTP/2.0","RetryAttempts":0,"ServiceName":"2-service@http","StartUTC":"2025-04-29T23:15:35.392421271Z","TLSCipher":"TLS_AES_128_GCM_SHA256","TLSVersion":"1.3","downstream_Content-Type":"","level":"info","msg":"","origin_Content-Type":"","request_Cookie":"REDACTED","request_User-Agent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:137.0) Gecko/20100101 Firefox/137.0","request_X-Forwarded-For":"<MYIP>","request_X-Forwarded-Proto":"https","request_X-Real-Ip":"172.70.43.54","time":"2025-04-29T23:15:36Z"}
```

**Comment by chris-coria** [comment]
Are you running gerbil and pangolin as "network_mode: host"? What's your docker-compose config?

**Comment by slimshizn** [comment]
I'm running the base install that is installed by the script.

**Comment by chris-coria** [comment]
Maybe running a traefik plugin to obtain headers? https://plugins.traefik.io/plugins/62947309108ecc83915d7784/traefik-get-real-ip

What I know is that cloudflare redirects IP in s "special header" so maybe a plugin can help catch it.

**Comment by overclockit** [comment]
So a different take on this issue specific to the whitelisting rules with Pangolin and Badger, My understanding, which could very well be wrong, is that the issue stems from Badger using &req.RemoteAddr, for RequestIP which is then used to determine whether the client IP should be allowed/blocked as set in Pangolin rules. When using this approach behind Cloudflare (Orange cloud), it returns the Cloudflare IP address instead of the client's IP.

My temporarily solution to this issue:

- Added Cloudflare's CIDR addresses to the trustedIPs setting in traefik_config.yml.
- Replaced instances of &req.RemoteAddr with clientIP in Badger's main.go file.
- Added clientIP := p.getClientIP(req) to func (p *Badger) ServeHTTP(rw http.ResponseWriter, req *http.Request) {
- Added a function to return Cf-Connecting-Ip or first IP in X-Forwarded-For in when set in the header in main.go.

```
func (p *Badger) getClientIP(req *http.Request) *string {
	ip := req.Header.Get("Cf-Connecting-Ip")
	if ip == "" {
		ip = req.Header.Get("X-Forwarded-For")
		if ip != "" {
			ip = strings.Split(ip, ",")[0] // Use the first IP from the list
		}
	}
	if ip == "" {
		ip = req.RemoteAddr
	}
	return &ip
}
```

Why this works in my setup:
- Ensures accurate client IP detection when behind Cloudflare’s proxy or other trusted proxy.
- Mitigates header spoofing risks by using trustedIPs.
- Prevents false whitelisting/blacklisting failures caused by relying solely on req.RemoteAddr.

This solution works for my setup using Cloudflare/Orange cloud. However, I'd like to note that if this solution were considered for actual use, it would be essential to enforce setting trustedIPs to mitigate the risks associated with forged headers.

**Comment by slimshizn** [comment]
This is still an issue.

**Comment by AstralDestiny** [comment]
It's related to badger not looking for X-Forwarded-For not anything to do with Traefik or Pangolin itself.

**Comment by AstralDestiny** [comment]
And should optionally not be set for just CF-Connecting-IP as that's an edge case, Sometimes servers might be down a few chains of reverse proxies or what not and should just look at X-Forwarded-For in the end for the actual data, It would fix Cloudflare too as Cloudflare sets the visitor ip if Traefik is configured to accept Cloudflare's ranges for headers, if not Traefik by design (security wise) will strip out any headers

**Comment by overclockit** [comment]
> And should optionally not be set for just CF-Connecting-IP as that's an edge case, Sometimes servers might be down a few chains of reverse proxies or what not and should just look at X-Forwarded-For in the end for the actual data, It would fix Cloudflare too as Cloudflare sets the visitor ip if Traefik is configured to accept Cloudflare's ranges for headers, if not Traefik by design (security wise) will strip out any headers

Agreed, really it should only ever use CF-Connecting-IP if the remoteAddr is within Cloudflare IP ranges. If X-Forwarded-For is present, it should only use the first untrusted IP from right to left, especially when there's the possibility of multiple upstream proxies just in case of misconfiguration and/or manipulation upstream.

**Comment by slimshizn** [comment]
Still an issue (stale bot needs to be disabled).

**Comment by jghaanstra** [comment]
I was hoping this would be solved in an upcoming release but unfortunately it didnt get any attention in the last two major releases. For me this is a pretty serious issue as it renders IP rules in the Pangolin rules engine useless when Cloudflare proxy is enabled. Is there something of a roadmap where I can see if and if so, when this planned?

This issue is marked as enhancement but it does not feel like an enhancement but much more like a bug.

**Comment by slimshizn** [comment]
https://github.com/fosrl/pangolin/issues/619#issuecomment-2881322127 seems to work, so maybe this is all that needs to be implemented.

**Comment by jghaanstra** [comment]
> https://github.com/fosrl/pangolin/issues/619#issuecomment-2881322127 seems to work, so maybe this is all that needs to be implemented.

I tried [this patched fork](https://plugins.traefik.io/plugins/6863251ba9d3b3a829cef53d/fossorial-badger-patch) of the Badger plugin that includes this fix but it only works if the client is using IPv4. When the client has a IPv6 address it still gets blocked by Pangolin even though it has been whitelisted in the Pangolin rules engine.

So that is something to look into when this bug is getting fixed in the Badger plugin.

**Comment by onno204** [comment]
Thanks, @jghaanstra!
I can confirm the [mentioned fork](https://github.com/hajimAIM/badger) is working perfect for me.

Thank you for the referral.

It is very easy to change the Traefik badger plugin and set up the forwarded headers
```
experimental:
  plugins:
    badger:
      # moduleName: "github.com/fosrl/badger"
      moduleName: "github.com/hajimAIM/badger"
      version: "v1.2.1"

entryPoints:
  web:
    address: ":80"
    forwardedHeaders:
      trustedIPs:
        - "10.10.10.10/32"
  websecure:
    address: ":443"
    forwardedHeaders:
      trustedIPs:
        - "10.10.10.10/32"
```
