### ISSUE TITLE
Local resources - Bad Gateway

### ISSUE THREAD

**Issue by pong106** [fosrl/pangolin#649]
Having `Bad Gateway` error when I spin up Portainer beside Pangolin. I setup using `local` site and `resource` with `127.0.0.1:9111`. Cant see any error in any loggings. Traefik dashboard works with the same method. Did not modify any `gerbil` settings.

docker-compose

```
services:
  portainer:
    image: portainer/portainer-ce:lts
    command: -H unix:///var/run/docker.sock
    restart: always
    networks:
      - pangolin
    ports:
      - "9111:9000"
      - "9443:9443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data

volumes:
  portainer_data:

networks:
  pangolin:
    external: true
```

**Comment by hermanops** [comment]
create resource with port 9443?

**Comment by pong106** [comment]
> create resource with port 9443?

tried with both 9111 and 9443 , same error.

**Comment by calim20** [comment]
Same here. I tried it with two different services, nginx and uptime-kuma. After authentication I get `Bad Gateway`.

I have created a `local` site with two resources. The nginx container I've started with `docker run` (`docker run -it --rm -d -p 8082:80 --name web nginx`) and for uptime-kuma I've used `docker compose`.

docker-compose.yml
```
services:
  uptime-kuma:
    restart: always
    ports:
      - 127.0.0.1:5001:3001
    volumes:
      - /data/uptime:/app/data
    container_name: uptime-kuma
    image: louislam/uptime-kuma:1
```

I've setup pangolin with crowdsec.

Best,
Marco
