### ISSUE TITLE
Having issues Wildcard Config for DNS-01 Challenge

### ISSUE THREAD

**Issue by 3ct0pl4sm** [fosrl/pangolin#670]
Hi, 
I'm trying to configure Wildcard Config for DNS-01 Challenge but I keep having the same error despite all of my attemps : 

> {"level":"error","providerName":"letsencrypt.acme","acmeCA":"https://acme-v02.api.letsencrypt.org/directory","providerName":"letsencrypt.acme","ACME CA":"https://acme-v02.api.letsencrypt.org/directory","routerName":"next-router@file","rule":"Host(`domain.com`) && !PathPrefix(`/api/v1`)","error":"cannot get ACME client cloudflare: some credentials information are missing: CLOUDFLARE_EMAIL,CLOUDFLARE_API_KEY or some credentials information are missing: CLOUDFLARE_DNS_API_TOKEN,CLOUDFLARE_ZONE_API_TOKEN","domains":["domain.com","*.domain.com"],"time":"2025-05-04T17:56:58Z","message":"Unable to obtain ACME certificate for domains"}

Cloudflare API Key is mentionned in docker-compose.yml as it is here :
[https://docs.fossorial.io/Pangolin/Configuration/wildcard-certs#wildcard-config-for-dns-01-challenge](url)
this way : 

```  
  traefik:
    image: traefik:v3.3.6
    container_name: traefik
    restart: unless-stopped
    network_mode: service:gerbil
    depends_on:
      pangolin:
        condition: service_healthy
    command:
      - --configFile=/etc/traefik/traefik_config.yml
    environment:
      CLOUDFLARE_DNS_API_TOKEN: "token"
    volumes:
      - ./config/traefik:/etc/traefik:ro
      - ./config/letsencrypt:/letsencrypt

```

Can someone help me ?

**Comment by boomam** [comment]
Are you using the in-built Traefik deployment, or an existing Traefik deployment?

**Comment by 3ct0pl4sm** [comment]
> Are you using the in-built Traefik deployment, or an existing Traefik deployment?

I'm using the built-in deployment.

I was restarting wrong the stack, I've figured it out, but now i've this error : 

`cloudflare: failed to create TXT record`

**Comment by 3ct0pl4sm** [comment]
I managed to make it work.
Thanks for your time and your answers.

**Comment by thimplicity** [comment]
> I managed to make it work. Thanks for your time and your answers.

Struggling with this - how did you make it work?

**Comment by boomam** [comment]
> > I managed to make it work. Thanks for your time and your answers.
> 
> Struggling with this - how did you make it work?

You need to set your traefik config to use DNS for its certificate challenge type.
Edit your Traefik configuration or your Traefik labels to use [DNS challenge](https://doc.traefik.io/traefik/https/acme/#dnschallenge) instead of the default HTTP challenge.

Pangolin has some ok docs on the process [here](https://docs.fossorial.io/Pangolin/Configuration/wildcard-certs#wildcard-config-for-dns-01-challenge)

**Comment by HWiese1980** [comment]
I have a problem with the Pangolin docs around this. The docs have the base domain in the next-router rule. However, the installer puts the pangolin web frontend subdomain in the next-router. This discrepancy leads to confusion. Just going with the docs, adding the domains to the `tls` subsection leads to errors (404 on the frontend after restarting the stack).

**Comment by HWiese1980** [comment]
Maybe someone could resolve this discrepancy? That would be awesome. I have my troubles figuring it out.

**Comment by HWiese1980** [comment]
Has anyone already looked into it? The documentation seems to be off here.

**Comment by mort666** [comment]
@HWiese1980 @thimplicity So something that I add to the certificatesResolvers section to make sure to add DNS resolvers that point to ones outside of my infrastructure. For some reason especially when running in docker traefik will mess up and fail to complete the certificate creation/renewal process if doing DNS-01 and it resolves against the docker inbuilt resolver. So basically my certificatesResolvers section looks something like:

```yaml
certificatesResolvers:
  letsencrypt:
    acme:
      email: hostmaster@example,com
      storage: /letsencrypt/acme.json
      caServer: https://acme-v02.api.letsencrypt.org/directory
      dnsChallenge:
        provider: cloudflare
        delayBeforeCheck: 0
        resolvers:
          - 1.1.1.1:53
          - 8.8.8.8:53
```
