### ISSUE TITLE
How to add a local domain?

### ISSUE THREAD

**Issue by ExXxtr3me** [fosrl/pangolin#689]
Hey, i just migrated all my services to a local only Pangolin from Zoraxy.
In Zoraxy, NPM, Caddy and so on i was able to add a local domain for some services that i only use locally, something like start.lan to access my homepage docker or music.lan for the music assistant. I'm not really sure how to replicate this with Pangolin, has anyone done that?

**Comment by ExXxtr3me** [comment]
Ok i figured it out, had to add the domain like this:

```
    domain4:
    base_domain: lan
    cert_resolver: letsencrypt
    prefer_wildcard_cert: false
```
