### ISSUE TITLE
[Support] Setup stack on Docker Swarm

### ISSUE THREAD

**Issue by srad** [fosrl/pangolin#709]
Do you have somewhere a compose file/documentation on how to setup the stack on a Docker Swarm cluster?
The default installer just uses plain Docker to setup and does not take Swarms into consideration.
I quickly tried to adapt the example compose file for Swarm but it did not work. Did anyone tried it yet?

**Comment by TuncTaylan** [comment]
Did you try this?
https://docs.docker.com/engine/swarm/stack-deploy/

**Comment by okfro** [comment]
This is the docker compose stack I use for Pangolin on Docker Swarm:

```
version: '3.8'

x-base: &base
  logging:
    driver: journald
  environment:
    TZ: ETC/UTC
  deploy:
    placement:
      constraints:
        # This assumes only 1 node is manager. This constraint should resolve to a single node.
        - node.role == manager
    restart_policy:
      condition: on-failure
      delay: 5s
  extra_hosts:
    # This is my Postgres instance IP. Only relevant if you are using postgres and you want a convenient shorthand to use as server name elsewhere in the configs.
    - primarydb:x.x.x.x
  networks:
    overnet:

# I deleted the default overlay network and recreated as "overnet". I did this to set up a specific IP subnet that is used for proxy protocol.
# The network should be whatever overlay network you use as your primary so that ingress works ootb
networks:
  overnet:
    external: true

services:

  pangolin:
    <<: *base
    image: fosrl/pangolin:ee-postgresql-latest
    hostname: pangolin
    healthcheck:
      interval: 10s
      retries: 15
      test:
        - CMD
        - curl
        - -f
        - http://localhost:3001/api/v1/
      timeout: 10s
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/var/run/docker.sock
      - ./config/pangolin:/app/config
      - ./logs/pangolin:/app/config/logs
      - ./config/traefik:/app/config/traefik
      - ./certs:/certs:ro
      - ./data/GeoIP:/GeoIP:ro
      - ./config/acme:/config/letsencrypt

  gerbil:
    <<: *base
    image: docker.io/fosrl/gerbil:latest
    hostname: gerbil
    command:
      - --reachableAt=http://gerbil:3004
      - --generateAndSaveKeyTo=/var/config/key
      - --remoteConfig=http://pangolin:3001/api/v1/
    volumes:
      - ./config/pangolin:/var/config
      - ./certs:/certs:ro
      - ./config/acme:/config/letsencrypt
    cap_add: [ALL]
    ports:
      - mode: host
        target: 51820
        published: 51820
        protocol: udp
      - mode: host
        target: 21820
        published: 21820
        protocol: udp

  traefik:
    <<: *base
    image: traefik:latest
    command:
      - --configFile=/etc/traefik/traefik_config.yml
    hostname: traefik
    depends_on:
      - gerbil
      - pangolin
    ports:
      - mode: host
        target: 80
        published: 80
        protocol: tcp
      - mode: host
        target: 443
        published: 443
        protocol: tcp
      - mode: host
        target: 443
        published: 443
        protocol: udp
      - mode: host
        target: 4190
        published: 4190
        protocol: tcp
      - mode: host
        target: 993
        published: 993
        protocol: tcp
      - mode: host
        target: 25
        published: 25
        protocol: tcp
      - mode: host
        target: 465
        published: 465
        protocol: tcp
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./config/traefik:/etc/traefik:ro
      - ./logs/traefik:/var/log/traefik
      - ./certs:/certs:ro
      - ./config/acme:/config/letsencrypt
    cap_add: [ALL]

  middleware-manager:
    <<: *base
    image: hhftechnology/middleware-manager:latest
    hostname: middleware-manager
    volumes:
      - ./data/middleware-manager:/data
      - ./config/traefik/rules:/conf
      - ./config/middleware-manager:/app/config
    environment:
      - PANGOLIN_API_URL=http://tasks.pangolin:3001/api/v1
      - TRAEFIK_CONF_DIR=/conf
      - DB_PATH=/data/middleware.db
      - PORT=3456

  # Traefik Log Dashboard Agent
  traefik-agent:
    <<: *base
    image: hhftechnology/traefik-log-dashboard-agent:latest
    # ports:
    #   - "5000:5000"
    volumes:
      - ./data/traefik/positions:/data
      - ./logs/traefik:/logs:ro
      - ./data/GeoIP:/geoip:ro
    environment:
      # Log Paths
      - TRAEFIK_LOG_DASHBOARD_ACCESS_PATH=/logs/access.log
      - TRAEFIK_LOG_DASHBOARD_ERROR_PATH=/logs/traefik.log
      # Authentication
      - TRAEFIK_LOG_DASHBOARD_AUTH_TOKEN=xxxxx
      # System Monitoring
      - TRAEFIK_LOG_DASHBOARD_SYSTEM_MONITORING=true
      # GeoIP Configuration
      - TRAEFIK_LOG_DASHBOARD_GEOIP_ENABLED=true
      - TRAEFIK_LOG_DASHBOARD_GEOIP_CITY_DB=/geoip/GeoLite2-City.mmdb
      - TRAEFIK_LOG_DASHBOARD_GEOIP_COUNTRY_DB=/geoip/GeoLite2-Country.mmdb
      # Log Format
      - TRAEFIK_LOG_DASHBOARD_LOG_FORMAT=json
      # Server Port
      - PORT=5000
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:5000/api/logs/status"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

  # Traefik Log Dashboard - Web UI
  traefik-dashboard:
    <<: *base
    image: hhftechnology/traefik-log-dashboard:latest
    # ports:
    #   - "3000:3000"
    environment:
      # Agent Configuration
      - AGENT_API_URL=http://tasks.traefik-agent:5000
      - AGENT_API_TOKEN=xxxxxx
      - NODE_ENV=production
      - PORT=3000
    depends_on:
      - traefik-agent
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3000"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
```

I haven't figured out how to route traffic through gerbil to traefik, so I only expose the Newt/Wireguard ports to the gerbil service. The rest of the config comes straight out of the docs. The `tasks.pangolin` path does not resolve from within the traffic config, but the hostname `pangolin` resolves just fine.

Then when it comes to Site and Public resource definitions, I have a local site (this will be local relative to the swarm node where the pangolin instance is running, and this doesn't need to be a manager node--it just happens to be in my example). Then each public resource targets `tasks.service_name` at its port. Every deployed service that you want to be public needs to be on the same overlay network as pangolin (in my case `overnet`).

Hopefully this is useful to someone else looking to do the same
