### ISSUE TITLE
How to use pangolin with Newt and local resources?

### ISSUE THREAD

**Issue by PilaScat** [fosrl/pangolin#768]
Hi, I have a VPS with Pangoling and Gerbil installed, it reaches my Newt servers, but I have Uptime Kuma on the same VPS, how can I reach both?
These are my networks:
![Image](https://github.com/user-attachments/assets/4fc35991-6e49-44d0-9980-92eb32706a8c)

**Comment by calim20** [comment]
Hi,
please see https://github.com/fosrl/pangolin/issues/649. You can reach local (docker) resources without using newt when they share the same network as pangolin. You can even use the container name for hostname.

**Comment by PilaScat** [comment]
> Hi, please see [#649](https://github.com/fosrl/pangolin/issues/649). You can reach local (docker) resources without using newt when they share the same network as pangolin. You can even use the container name for hostname.

Thank you, I used:
```
services:
  uptime-kuma:
    restart: always
    networks:
      - pangolin
    volumes:
      - /uptime:/app/data
    container_name: uptime-kuma
    image: louislam/uptime-kuma

networks:
  pangolin:
    external: true
```
But for now I still got Bad Gateway
