### ISSUE TITLE
newt resource gives bad gateway

### ISSUE THREAD

**Issue by tobias-carlbom** [fosrl/pangolin#917]
hi,

this project seems very interesting! but i cannot get site resource to work.

i tried the following in both casaos and portainer:
```
services:
  newt:
    image: fosrl/newt
    container_name: newt
    restart: unless-stopped
    environment:
      - PANGOLIN_ENDPOINT=https://myserver.abc
      - NEWT_ID=ozbo6c2ny6vnhvd
      - NEWT_SECRET=ol21vivpt1tdqcfoyrv7ii37pba0akwe6td8locska2e7mv5
```

in pangolin dashboard i can see that site is online. also in newt container logs it looks fine, no errors, it pings.

i have added a local resource  on either the casaos or portainer host and added a subdomain (test.myserver.abc) on my domain provider. when i try to access test.myserver.abc (without any protection) i get Bad Gateway.

vps ufw rules:
```
443/tcp                    ALLOW       Anywhere                  
80/tcp                     ALLOW       Anywhere                  
51821/udp                  ALLOW       Anywhere                  
443/udp                    ALLOW       Anywhere                  
51821/tcp                  ALLOW       Anywhere                  
53                         ALLOW       Anywhere                  
8085/tcp                   ALLOW       Anywhere                  
51820/udp                  ALLOW       Anywhere                  
443/tcp (v6)               ALLOW       Anywhere (v6)             
80/tcp (v6)                ALLOW       Anywhere (v6)             
51821/udp (v6)             ALLOW       Anywhere (v6)             
443/udp (v6)               ALLOW       Anywhere (v6)             
51821/tcp (v6)             ALLOW       Anywhere (v6)             
53 (v6)                    ALLOW       Anywhere (v6)             
8085/tcp (v6)              ALLOW       Anywhere (v6)             
51820/udp (v6)             ALLOW       Anywhere (v6)             

administrator@vsvr0122:~$ 
```

on my homelab router i have not created any port forwarding rules btw

what am i doing wrong?
