### ISSUE TITLE
Low download and upload speed

### ISSUE THREAD

**Issue by victorvs0uz4** [fosrl/pangolin#924]
Hello,
I recently closed a connection between my VPS and my LAN network using a Proxmox LXC container, but when I performed some download and upload tests on Nextcloud, the speeds did not exceed 100Mbps. Is there any way to change Newt's MTU?

I think it must be limiting.

**Comment by oschwartz10612** [comment]
Yes! You can change the mtu on both the Gerbil and Newt side (make sure to keep both the same) using the --mtu or MTU env vars. I think its not in the docs but we should add it.

**Comment by oschwartz10612** [comment]
Let me know if it improves the speed but I think the general performance is in this area due to the user space networking and proxy. We plan on maybe doing a native tunnel at some point but for now you could experiment with raw WG for speed.

**Comment by victorvs0uz4** [comment]
Okay, how do I change Gerbil's MTU? Would it be via docker-compose?

**Comment by oschwartz10612** [comment]
Yep same --mtu or MTU env var (I would use the var)

**Comment by victorvs0uz4** [comment]
sorry, can you give an example of how I can set it?

**Comment by oschwartz10612** [comment]
```
services:
  gerbil:
    image: fosrl/gerbil
    container_name: gerbil
    restart: unless-stopped
    environment:
      - MTU=1280                          <-----------------
    command:
      - --reachableAt=http://gerbil:3003
      - --generateAndSaveKeyTo=/var/config/key
      - --remoteConfig=http://pangolin:3001/api/v1/gerbil/get-config
      - --reportBandwidthTo=http://pangolin:3001/api/v1/gerbil/receive-bandwidth
    volumes:
      - ./config/:/var/config
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    ports:
      - 51820:51820/udp
```
