### ISSUE TITLE
Newt cant connect to server 

### ISSUE THREAD

**Issue by Joksa98** [fosrl/pangolin#951]
**Environment:**
* **Pangolin Version:** 1.5.1
* **Gerbil Version:** 1.0.0
* **Newt Version:** 1.2.1
* **Setup:** Pangolin server running on a public VPS. Newt client running locally in a Docker stack.

---

### Problem Description

I've setup pangolin using automatic installer on a VPS and it works, but when i add new site and try to run and connect newt it cant ping server 100.89.128.1 

#### Newt Client Log:
```LOGS
newt  | INFO: 2025/06/22 13:18:55 Newt version 1.2.1
newt  | INFO: 2025/06/22 13:19:00 Sent registration message
newt  | INFO: 2025/06/22 13:19:00 Received registration message
newt  | INFO: 2025/06/22 13:19:00 Received: {Type:newt/wg/connect Data:map[endpoint:pangolin.example.com:51820 publicKey:*********** serverIP:100.89.128.1 targets:map[tcp:[] udp:[]] tunnelIP:100.89.128.4]}
newt  | INFO: 2025/06/22 13:19:01 WireGuard device created. Lets ping the server now...
newt  | INFO: 2025/06/22 13:19:01 Ping attempt 1
newt  | INFO: 2025/06/22 13:19:01 Pinging 100.89.128.1
newt  | WARN: 2025/06/22 13:19:11 Ping attempt 1 failed: failed to read ICMP packet: i/o timeout
newt  | INFO: 2025/06/22 13:19:11 Starting ping check
newt  | INFO: 2025/06/22 13:19:11 Ping attempt 2
newt  | INFO: 2025/06/22 13:19:11 Pinging 100.89.128.1
newt  | WARN: 2025/06/22 13:19:21 Ping attempt 2 failed: failed to read ICMP packet: i/o timeout
newt  | INFO: 2025/06/22 13:19:23 Ping attempt 3
newt  | INFO: 2025/06/22 13:19:23 Pinging 100.89.128.1
newt  | WARN: 2025/06/22 13:19:33 Ping attempt 3 failed: failed to read ICMP packet: i/o timeout
newt  | INFO: 2025/06/22 13:19:35 Ping attempt 4
newt  | INFO: 2025/06/22 13:19:35 Pinging 100.89.128.1
newt  | INFO: 2025/06/22 13:19:41 Pinging 100.89.128.1
newt  | WARN: 2025/06/22 13:19:45 Ping attempt 4 failed: failed to read ICMP packet: i/o timeout
newt  | INFO: 2025/06/22 13:19:47 Ping attempt 5
newt  | INFO: 2025/06/22 13:19:47 Pinging 100.89.128.1
newt  | WARN: 2025/06/22 13:19:51 Connection to server lost. Continuous reconnection attempts will be made.
newt  | WARN: 2025/06/22 13:19:51 Please check your internet connection and ensure the Pangolin server is online.
newt  | WARN: 2025/06/22 13:19:51 Newt will continue reconnection attempts automatically when connectivity is restored.
newt  | WARN: 2025/06/22 13:19:57 Ping attempt 5 failed: failed to read ICMP packet: i/o timeout
newt  | INFO: 2025/06/22 13:19:57 Increasing ping retry delay to 3s
newt  | INFO: 2025/06/22 13:20:00 Ping attempt 6
newt  | INFO: 2025/06/22 13:20:00 Pinging 100.89.128.1
newt  | WARN: 2025/06/22 13:20:10 Ping attempt 6 failed: failed to read ICMP packet: i/o timeout
newt  | INFO: 2025/06/22 13:20:11 Pinging 100.89.128.1
newt  | INFO: 2025/06/22 13:20:13 Ping attempt 7
newt  | INFO: 2025/06/22 13:20:13 Pinging 100.89.128.1
newt  | WARN: 2025/06/22 13:20:23 Ping attempt 7 failed: failed to read ICMP packet: i/o timeout
```

---

### Configurations

I've replaces my domain with example.com but i use domain.duckdns.org.

**1. Pangolin Server `docker-compose.yml` (on VPS)**
```yaml
name: pangolin
networks:
  default:
    driver: bridge
    name: pangolin
services:
  crowdsec:
    # ... crowdsec config ...
  gerbil:
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    command:
      - --generateAndSaveKeyTo=/var/config/key
      - --remoteConfig=http://pangolin:3001/api/v1/gerbil/get-config
      - --reportBandwidthTo=http://pangolin:3001/api/v1/gerbil/receive-bandwidth
    container_name: gerbil
    depends_on:
      pangolin:
        condition: service_healthy
    image: fosrl/gerbil:1.0.0
    ports:
      - 51820:51820/udp
      - 443:443
      - 80:80
    restart: unless-stopped
    volumes:
      - ./config/:/var/config
  pangolin:
    # ... pangolin config ...
  traefik:
    # ... traefik config ...
```

**2. Pangolin Server `config.yml` (on VPS)**
```yaml
app:
   dashboard_url: "https://pangolin.example.com"
   log_level: "info"

domains:
   domain1:
       base_domain: "example.com"
       cert_resolver: "myresolver"

server:
   secret: "a_very_long_and_random_secret_key"
   # ... other server config ...

traefik:
   cert_resolver: "myresolver"
   http_entrypoint: "web"
   https_entrypoint: "websecure"

gerbil:
   start_port: 51820
   base_endpoint: "pangolin.example.com"
   use_subdomain: true
   block_size: 24
   site_block_size: 30
   subnet_group: 100.89.137.0/20

users:
   server_admin:
       email: "admin@example.com"
       password: "a-secure-password"

# ... other flags ...
```

**3. Newt Client `docker-compose.yml` (Local Machine)**
```yaml
services:
  gluetun:
    # ... gluetun config ...

  newt:
    image: fosrl/newt
    container_name: newt
    restart: unless-stopped
    network_mode: "service:gluetun" # Routing through VPN
    depends_on:
      - gluetun
    environment:
      - PANGOLIN_ENDPOINT=https://pangolin.example.com
      - NEWT_ID=REDACTED
      - NEWT_SECRET=REDACTED

  # ... other local services ...
```
